FDK/Tools/SharedData/FDKScripts/ufoTools.py
This fixes a crash with FontForge-generated UFOs.
r? @readroberts
=> ufoTools: don't crash on GLIF files with no outline element

FDK/Tools/SharedData/FDKScripts/otf2otc.py
The current otf2otc.py script produces misaligned sfnt tables because it does not align offsets to 4-byte boundaries.
Here's an excerpt from http://www.microsoft.com/typography/otspec/otff.htm
> the length of a table must be a multiple of four bytes. In fact, a font is not considered structurally proper without the correct padding. All tables must begin on four byte boundaries, and any remaining space between tables is padded with zeros. The length of all tables should be recorded in the table record with their actual length (not their padded length).
I modified it to add padding where required.
Cheers,
Cosimo
=> [otf2ofc.py] pad table data to multiple of four bytes in accordance with OT specs

FDK/Tools/Programs/public/config/linux/gcc/gcc.mak, FDK/Tools/Programs/public/lib/config/linux/gcc/gcc.mak, FDK/Tools/Programs/public/lib/config/linux/gcc/gcc_tx.mak, FDK/Tools/Programs/sfntdiff/build/linux/gcc/debug/Makefile, FDK/Tools/Programs/sfntdiff/build/linux/gcc/release/Makefile, FDK/Tools/Programs/sfntedit/build/linux/gcc/debug/Makefile, FDK/Tools/Programs/sfntedit/build/linux/gcc/release/Makefile, FDK/Tools/Programs/spot/build/linux/gcc/debug/Makefile, FDK/Tools/Programs/spot/build/linux/gcc/release/Makefile
Code in the FDK depends on the assumption that it will be compiled on a 32 bit platform. Until someone decides to actually remove all the 32bit-dependent code from the FDK, these flags should remain.
Fixes issue #48
=> Revert "Remove 32bit architecture dependence"

FDK/Tools/Programs/tx/source/help.h
The Windows tempfile permissions issue was fixed with the inclusion of a custom `_tmpfile` function, therefore the paragraph in `tx -h` doesn't apply any more.
=> [tx] remove reference to Windows permissions issue from help.h

FDK/Tools/Programs/autohint/build/osx/xcode4/autohintexe.xcodeproj/project.pbxproj
For some reason, the Xcode project for autohint was looking for libautohintlib using an explicit path to a DerivedData directory under ~/Library. This caused a build failure for anyone who didn't have the library compiled in that exact place.
This should hopefully fix that, by changing the build to find that library via its subproject.
=> Fix libautohintlib path in Xcode project.

FDK/Tools/Programs/makeotf/makeotf_lib/source/hotconv/GPOS.c, FDK/Tools/Programs/makeotf/makeotf_lib/source/hotconv/GSUB.c
Do not require Mac name ID's for feature names and size feature as well, see #58.
=> Do not require Mac name ID's for feature names

FDK/FDK Build Notes.txt
Build notes on MutatorMath mention a bug in the setup script of defcon. It has been fixed since on both master (typesupply/defcon@9f747f1e23110e38c525632fd8aa8ee077e314c3) and ufo3 branch (typesupply/defcon@4f8777c25d9a52965227b488bc505dfce991adf9).
=> Update MutatorMath installation instructions

FDK/Tools/Programs/spot/source/GPOS.c, FDK/Tools/Programs/spot/source/proof.c
Proofing command: 'spot -Pvkrn GroupKern.otf > GroupKern.ps'
result (left: current version, right: after modified) :
=> vertical width was not referred when proofing group-based vkrn lookups

FDK/Tools/SharedData/FDKScripts/MakeOTF.py
This is checking the wrong path. For CFF fonts it doesn't make a
difference, tempOutPath and outputPath are the same. But for TrueType
fonts tempOutPath points to a temporary CFF font which should have
been deleted, thus it always thinks TTF generation has failed.
=> Check correct output path for makeotf failure

FDK/Tools/SharedData/FDKScripts/makeInstancesUFO.py
The `ufonormalizerLib` import name changed to `ufonormalizer` in commit 28c50d7.
Line 419 was changed accordingly, but the call on 436 was missed. This commit fixes that.
=> Fix broken ufonormalizer call

FDK/Technical Documentation/OpenTypeFeatureFileSpecification.html
readroberts wrote on Sep 25, 2015: "About the 31 character limit in
PostScript glyph names: although the spec clearly states the limit of
31 characters, I increased the limit in the AFDKO tools to 63 a year
or to ago for practical reasons. Use of the rules to name complex
ligatures leads to longer glyph names, and I had reasonable use cases
that would exceed this limit. A number of the limits stated in the
spec are not in fact enforced any the rasterizes I have available for
testing. I changed this limit in the AFDKO tools in order to test if
we could in practice get away with longer glyph names. Although there
are few such cases, I have not heard of any reports of difficulties. I
agree that the spec should be changed."
https://github.com/fontforge/fontforge/pull/2500#issuecomment-14326339 …
=> Allow glyph names with up to 63 characters

FDK/Tools/SharedData/FDKScripts/CheckOutlinesUFO.py
This allows using the script as a module.
```python
from CheckOutlinesUFO import run as checkoutlinesufo
checkoutlinesufo(['-e', myFont.ufo])
```
=> [CheckOutlinesUFO] pass in the command line arguments

afdko/Tools/SharedData/FDKScripts/CheckOutlinesUFO.py
Now using defcon_font.keys() if no glyph list specified, and defcon_font.glyphOrder if the glyph list is specified.
Also added an error message for when the glyph list is specified and the defcon_font.glyphOrder is empty or missing.
=> Improvements in CheckOutlinesUFO glyph list handling:

afdko/Tools/SharedData/FDKScripts/CheckOutlinesUFO.py, afdko/Tools/SharedData/FDKScripts/ufoTools.py
now reporting a warning about skipping a glyph that is not in the UFO glyph map rather than crashing with an error.
=> Fix for issue #228:

afdko/Tools/SharedData/FDKScripts/BezTools.py, afdko/Tools/SharedData/FDKScripts/ConvertFontToCID.py, afdko/Tools/SharedData/FDKScripts/FDKUtils.py, afdko/Tools/SharedData/FDKScripts/MakeOTF.py, afdko/Tools/SharedData/FDKScripts/StemHist.py, afdko/Tools/SharedData/FDKScripts/autohint.py, afdko/Tools/SharedData/FDKScripts/buildMasterOTFs.py, afdko/Tools/SharedData/FDKScripts/ufoTools.py
there are still lots of improvements to make:
with open(path, "wr") as f:
f.read / f.write
lots of open files warnings...
https://github.com/adobe-type-tools/afdko/issues/231
=> partially making in py3 ready

afdko/Tools/Programs/makeotf/makeotf_lib/api/hotconv.h, afdko/Tools/Programs/makeotf/makeotf_lib/source/hotconv/GSUB.c, afdko/Tools/Programs/makeotf/makeotf_lib/source/typecomp/parse.c, afdko/Tools/Programs/makeotf/source/main.c, afdko/Tools/SharedData/FDKScripts/MakeOTF.py
multiply first digit of cv number by 10 instead of shifting left by 8 bits, so now we get a cv number of 10 instead of 256 for cv10.
=> Fix for issue #237:

afdko/Tools/SharedData/FDKScripts/buildCFF2VF.py
aka derived from CID-keyed CFF fonts.
=> [buildCFF2VF] Fix support for CFF2 fonts with multiple FontDicts

README.rst
This reverts commit 209e413b20578b2a2a8e62991f5741f5dded936d.
The red banner is gone.
=> Revert "update PyPI URL in README.rst"

.travis.yml, requirements.txt, setup.py
This way there's less scrolling to get to failing tests, and the coverage is reported for the source files, not for the installed ones.
=> Move wheel-making and -installation to later in the process

.travis.yml
not sure why for the other osx-deploy build, it doesn't complain that there is no 'script' step defined...
anyway, let's try one more time.
=> travis: also skip 'script' step, all the work happens in before_deploy

afdko/Tools/Programs/public/lib/source/cffread/cffread.c
Initialize info.cid for each glyph in CID/CFF2 font with its gid, otherwise when converting CFF2 to CFF1, cfwAddGlyph in cffwrite.c regards all glyphs as CID = 0, optimize away all font dicts except font dict 0 for CID 0 as unused (see lines around comment "Force CID 0 to GID 0" at line 576 in cffwrite.c).
=> fix for #329 [tx] fail to convert multi-FD CFF2 font to CID/CFF

.travis.yml
Available versions at https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
This is to force the wheel to support macOS 10.10 and above; current support is 10.12+
=> [travis] Specify osx_image

afdko/Tools/SharedData/FDKScripts/ttxn.py
Bug introduced in b3ca003471fe137cb972fde18196ef42cd5e2f65
Fixes #350
=> [ttxn] ClassRecord attribute 'type' is now called 'side'

afdko/Tools/Programs/tx/source/tx.c
Otherwise stem hints are written out with the default values of CFF2 variable stem hints when we want blended hints snapshotted for the current instance in the output.
=> nullify glyph stemVF callback when not writing CFF2

README.md
=> AppVeyor & CodeCov badges now show status of `develop`

Tests/spot_test.py, afdko/Tools/Programs/spot/source/GDEF.c, afdko/Tools/Programs/spot/source/GPOS.c, afdko/Tools/Programs/spot/source/GSUB.c, afdko/Tools/Programs/spot/source/SING.c, afdko/Tools/Programs/spot/source/cmap.c, afdko/Tools/Programs/spot/source/global.c, afdko/Tools/Programs/spot/source/global.h, afdko/Tools/Programs/spot/source/map.c, afdko/Tools/Programs/spot/source/opt.c, afdko/Tools/Programs/spot/source/proof.c
With the 64-bit update, the function global.c::getGlyphName() can return a glyph name of up to 128+7 characters long. The returned string was, in many places, copied into a string buffer that was much shorter. Fixes issue 373.
=> [spot] Fix a crash due to buffer overrun errors from long glyph names.

.appveyor.yml
Ilya Finkelshteyn said that the code removed by this commit is no longer needed now that https://github.com/appveyor/ci/issues/2066 is fixed.
(This is round 2, because I'm trying again off a fresh branch from `develop`.)
=> Remove obsolete AppVeyor code (round 2)

setup.py
we need to skip the step where python3's distutils attempts to fix up the script's shebang, otherwise it fails with a SyntaxError, since it expects them to be text (shell or python) files, whereas in our case they are simply C binary executables.
the code is based on the latest cpython distutils:
https://github.com/python/cpython/blob/master/Lib/distutils/command/build_scripts.py
this is the error that python3.6 throws when one attempts to create a wheel from the afdko source, without this patch:
```
running build_scripts
creating build/scripts-3.6
Traceback (most recent call last):
File "/home/clupo/.pyenv/versions/afdko-py36/lib/python3.6/tokenize.py", line 390, in find_cookie
line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 32: …
```
=> setup.py: allow to install native exe scripts on python3

afdko/Tools/Programs/autohint/build/linux/gcc/BuildAll.sh, afdko/Tools/Programs/autohint/build/osx/xcode4/BuildAll.sh, afdko/Tools/Programs/detype1/build/linux/gcc/BuildAll.sh, afdko/Tools/Programs/detype1/build/osx/xcode4/BuildAll.sh, afdko/Tools/Programs/makeotf/build/linux/gcc/BuildAll.sh, afdko/Tools/Programs/makeotf/build/osx/xcode4/BuildAll.sh, afdko/Tools/Programs/mergeFonts/build/linux/gcc/BuildAll.sh, afdko/Tools/Programs/mergeFonts/build/osx/xcode4/BuildAll.sh, afdko/Tools/Programs/rotateFont/build/linux/gcc/BuildAll.sh, afdko/Tools/Programs/rotateFont/build/osx/xcode4/BuildAll.sh, afdko/Tools/Programs/sfntdiff/build/linux/gcc/BuildAll.sh, afdko/Tools/Programs/sfntdiff/build/osx/xcode4/BuildAll.sh, afdko/Tools/Programs/sfntedit/build/linux/gcc/BuildAll.sh, afdko/Tools/Programs/sfntedit/build/osx/xcode4/BuildAll.sh, afdko/Tools/Programs/spot/build/linux/gcc/BuildAll.sh, afdko/Tools/Programs/spot/build/osx/xcode4/BuildAll.sh, afdko/Tools/Programs/tx/build/linux/gcc/BuildAll.sh, afdko/Tools/Programs/tx/build/osx/xcode4/BuildAll.sh, afdko/Tools/Programs/type1/build/linux/gcc/BuildAll.sh, afdko/Tools/Programs/type1/build/osx/xcode4/BuildAll.sh
Otherwise it is not of much use; appending `debug` to build command in `setup.py` will fail with missing executables.
=> Copy executables in debug build target as well

afdko/Technical Documentation/OpenTypeFeatureFileSpecification.html
Add link to “markClass” in TOC.
Fix links to “subtable” and “Examples” in TOC.
=> Spec: add missing “markClass” to TOC

requirements.txt
Cap the version of ufoLib until Cosimo revises his approach in the new `ufoLib.plistlib`. See #486.
=> Cap ufoLib version to 2.1.1

Tests/spot_test.py, afdko/Tools/Programs/spot/source/GPOS.c, afdko/Tools/Programs/spot/source/main.c
=> [spot] Fix spot crash with 'spot -t GPOS -6 <any font>'

afdko/Technical Documentation/OpenTypeFeatureFileSpecification.html
…o makeotf
Removed the restriction that 'DFLT' script is allowed to have only the 'dflt' language. This now matches the changes made for version 1.8.2 of the OpenType spec.
Removed the restriction that that all mark-to-base statements in a lookup and mark-to-mark must reference the the same set of mark glyph classes.
=> [fea spec] Update to reflect changes in OT spec and makeotf

Tests/makeotf_data/input/bug438/feat.fea, Tests/makeotf_test.py, afdko/Tools/Programs/makeotf/makeotf_lib/source/hotconv/feat.c
=> Allow any language with DFLT script

.gitignore
(otherwise changes in matching folders don't get picked up, e.g. in the `tx` folder)
I realized we had a problem after a comment that @anthrotype made in this thread: https://github.com/typemytype/booleanOperations/issues/40#issuecomment-408395042)
=> use explicit paths for ignoring compiled OSX & linux programs

python/afdko/autohint.py
=> [autohint] Fix temp files solution

c/detype1/source/detype1.c, tests/detype1_test.py, tests/runner.py, tests/runner_test.py
=> [detype1] Fix exit code for known options

c/spot/source/CFF_.c, tests/spot_data/expected_output/dump_CFF_=6s.ps, tests/spot_test.py
[spot] CFF table differences between Mac/Win
Fixes #469
The text writing code uses printf formatting statements to round some values. On Mac, x.5 rounds down, on Win, x.5 rounds up.
Use std lib round() function to round arguments before they are passed to the printf function.
=> [spot] CFF table differences between Mac/Win

c/detype1/source/detype1.c, c/type1/source/type1.c, tests/runner.py, tests/runner_test.py, tests/type1_test.py
=> [type1] Implement '-h' option. Fix exit code for known options

c/spot/source/main.c, c/spot/source/name.c, tests/spot_data/expected_output/dump_name=3.txt, tests/spot_data/expected_output/dump_name=4.txt, tests/spot_test.py
Fixes issue 468
spot sorted the name records by offset to the string, rather than name record order. If the offsets for two different names are the same, then the qsort is unstable, and Windows sorts differently than Mac. The fix is to NOT sort, and report the records by name record order.
The logic was originally an optimization for name table dumps other than level 3, as report of a name string could be omitted if it the name strings were sorted by offset, and the offset of the current record was the same as the previous record. However, we now think it more valuable to have one string dump per name record, and for the strings to be reported in name record order.
=> [spot] name table difference between Mac/Win spot 

c/public/lib/api/t1read.h, c/public/lib/source/t1read/t1read.c, tests/rotatefont_test.py
[rotatefont] Failures on Linux c-tools 
fixes #569
Fixed by setting the buffer length to 0 after the first pass of parsing
so that the src charstring data will get reloaded again.
If the font is a Type1 CID font, the glyph data (charstrings) must be
read when building a subset, in order to get the FD index. When a CID
charstring is read, it is decrypted in place in the src buffer. If the
total charstring data is smaller than the src buffer, then when the
glyph data is later read again when the subset is applied, the existing
charstring data is just copied from the buffer, rather than being read
from file into the buffer. However, the data is then already decrypted,
and applying decryption again produces garbage data.
This is an old bug, and can occur on Mac and Windows as well as Linux. …
=> [rotatefont] Failures on Linux c-tools 

c/autohint/build/linux/gcc/BuildAll.sh, c/autohint/build/osx/xcode4/BuildAll.sh, c/buildall.sh, c/buildalllinux.sh, c/detype1/build/linux/gcc/BuildAll.sh, c/detype1/build/osx/xcode4/BuildAll.sh, c/makeotf/build/linux/gcc/BuildAll.sh, c/makeotf/build/osx/xcode4/BuildAll.sh, c/mergefonts/build/linux/gcc/BuildAll.sh, c/mergefonts/build/osx/xcode4/BuildAll.sh, c/rotatefont/build/linux/gcc/BuildAll.sh, c/rotatefont/build/osx/xcode4/BuildAll.sh, c/sfntdiff/build/linux/gcc/BuildAll.sh, c/sfntdiff/build/osx/xcode4/BuildAll.sh, c/sfntedit/build/linux/gcc/BuildAll.sh, c/sfntedit/build/osx/xcode4/BuildAll.sh, c/spot/build/linux/gcc/BuildAll.sh, c/spot/build/osx/xcode4/BuildAll.sh, c/tx/build/linux/gcc/BuildAll.sh, c/tx/build/osx/xcode4/BuildAll.sh, c/type1/build/linux/gcc/BuildAll.sh, c/type1/build/osx/xcode4/BuildAll.sh
Out of all the files in the `c` folder, the only two with a grade of "F" on Codacy were shell scripts, so I cleaned up all the shell scripts to get a clean report from `shellcheck` (the tool used by Codacy to analyze shell scripts).
=> cleaned up issues reported by shellcheck

.appveyor.yml
Hopefully this change will speedup AppVeyor a bit by not letting it create a branch job when changes are made to a branch that has an open PR already.
Travis seems to do this by default.
=> [appveyor] Set skip_branch_with_pr

.travis.yml, c/autohint/autohintlib/source/ac/memcheck.c, c/autohint/autohintlib/source/public/extras/numtypes.h, c/autohint/autohintlib/source/public/extras/pubtypes.h, c/public/lib/api/supportpublictypes.h
* modernized some typedefs to use `int32_t`, `int16_t`, etc.
* removed a lot of unused code from `supportpublictypes.h`
=> fix typedefs

NEWS.md
Making fix in 'master' to avoid conflict when trying to merge 'release'.
This change was originally made in 4590c75e603362b63a8c71bf01dd9ef5cabd2c12
=> Fix release date

setup.cfg, setup.py
the afdko doesn't include any extenstion modules, only native C executables. These are independent from the Python version, they only depend on the system's platform and architecture (32 vs 64 bit).
You can greatly reduce the number of wheel packages that you build and publish if you name the wheels with a "universal" `py2.py3` tag, an ABI tag of "none" (meaning it does not depend on CPython ABI), and with a platform tag that reflects the different platforms and architecture supported (Linux, MacOS, Windows, 32 vs 64 bit, etc. all automatically selected by bdist_wheel command).
I used the same approach in ttfautohint-py, where I bundle a DLL of libttfautohint (wrapped via ctypes). It reduced the number of wheels I publish to only 4: 1 for macOS (a fat "intel" binary including both 32 and …
=> setup.py: build 'universal' py2.py3 wheels

pyproject.toml, tests/tx_test.py
The test tx_test.py::test_convert() tests were failing when converting ufo to PDF, because the positioning of the data and time stamps on the PDF page changed with the change of current date to Oct.:
```
498.50 30.00 Td
(Date:  24 Aug 18)'
16.00 0.00 Td
(Time:  14:53)'
```
Added regex's to skip the positioning lines containing '0.00 Td' and '30.00 Td', which are unique on the page and do not change with the date.
=> Fix outdated tests

python/afdko/makeinstancesufo.py
```python
Traceback (most recent call last):
File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "c:\Program Files\Python36\Scripts\makeInstancesUFO.exe\__main__.py", line 9, in <module>
File "c:\program files\python36\lib\site-packages\afdko\makeinstancesufo.py", line 421, in main
run(sys.argv[1:])
File "c:\program files\python36\lib\site-packages\afdko\makeinstancesufo.py", line 389, in run
postProcessInstance(instancePath, options)
File "c:\program files\python36\lib\site-packages\afdko\makeinstancesufo.py", line 357, in postProcessInstance
clearCustomLibs(dFont)
File "c:\program files\python36\lib\site-packages\afdko\makeinstancesufo.py", …
```
=> [makeinstancesufo] Fix RuntimeError

c/public/lib/source/t1write/t1write.c
This is just some minor code cleanup, per feedback from @readroberts in https://github.com/adobe-type-tools/afdko/pull/656.
=> make line metrics callback more consistent with move and curve

c/public/lib/source/tx_shared/tx_shared.c, tests/tx_data/expected_output/cff2_vf.dcf.txt
Fix for the issue #678.
Attached a new output from a command line:
`tx -dcf AdobeVFPrototype.abc.subr.otf`
[after.dcf.txt](https://github.com/adobe-type-tools/afdko/files/2568870/after.dcf.txt)
=> fix for [tx] -dcf fails to print CFF2 global subrs #678

c/public/lib/source/cffwrite/cffwrite_subr.c
use "unsigned" in place of "unsigned short" as type of offsets and lengths
verified the fix using the attached CFF2 font uni7e7c.otf
=> fix issue #685 [tx] subroutinizer 64K limit

c/makeotf/makeotf_lib/source/hotconv/otl.c
On my system, `makeotfexe_test.py` enters into, what appears to be, an infinite loop in test_duplicate_single_sub test.
This seems to be caused by `nFeatures` variable in `fillFeatureList()` getting a random huge value when there are no features in the file, as `spanLimit` can be 0 and the code ends up trying to access `t->subtable.array[-1].index.feature`.
=> [makeotfexe] Fix infinite loop

python/afdko/makeotf.py
The `sfntedit` tool creates temporary files with fixed names in the current working directory, which breaks running multiple `makeotf` instances in parallel (e.g. from a makefile). Using FontTools fixes this limitation.
=> [makeotf] Use FontTools to copy font tables

docs/OpenTypeFeatureFileSpecification.html
As a follow up to [[feaLib] Support subtable statement in more places](https://github.com/fonttools/fonttools/pull/1520). This changes the description of the `subtable` statement, allowing it for other than PairPos Format 2, in which case it may be ignored by implementation software.
=> Allow 'subtable' statement in other than PairPos Format 2

setup.py
get_executable_dir() is only used in one place to decide which build script to use.
=> Simplify setup.py a bit

python/afdko/makeotf.py
Minor (undocumented) feature of `makeotf`: the default `features` file may have a suffix (which helps with detecting syntax coloring).
=> [makeotf] features file may have a suffix

c/mergefonts/build/osx/xcode/mergeFonts.xcodeproj/project.pbxproj, c/public/lib/build/absfont/osx/xcode/absfont.xcodeproj/project.pbxproj, c/public/lib/build/cfembed/osx/xcode/cfembed.xcodeproj/project.pbxproj, c/public/lib/build/cffread/osx/xcode/cffread.xcodeproj/project.pbxproj, c/public/lib/build/cffwrite/osx/xcode/cffwrite.xcodeproj/project.pbxproj, c/public/lib/build/ctutil/osx/xcode/ctutil.xcodeproj/project.pbxproj, c/public/lib/build/dynarr/osx/xcode/dynarr.xcodeproj/project.pbxproj, c/public/lib/build/nameread/osx/xcode/nameread.xcodeproj/project.pbxproj, c/public/lib/build/pdfwrite/osx/xcode/pdfwrite.xcodeproj/project.pbxproj, c/public/lib/build/pstoken/osx/xcode/pstoken.xcodeproj/project.pbxproj, c/public/lib/build/sfntread/osx/xcode/sfntread.xcodeproj/project.pbxproj, c/public/lib/build/sfntwrite/osx/xcode/sfntwrite.xcodeproj/project.pbxproj, c/public/lib/build/sha1/osx/xcode/sha1.xcodeproj/project.pbxproj, c/public/lib/build/support/osx/xcode/support.xcodeproj/project.pbxproj, c/public/lib/build/svgwrite/osx/xcode/svgwrite.xcodeproj/project.pbxproj, c/public/lib/build/svread/osx/xcode/svread.xcodeproj/project.pbxproj, c/public/lib/build/t1cstr/osx/xcode/t1cstr.xcodeproj/project.pbxproj, c/public/lib/build/t1read/osx/xcode/t1read.xcodeproj/project.pbxproj, c/public/lib/build/t1write/osx/xcode/t1write.xcodeproj/project.pbxproj, c/public/lib/build/t2cstr/osx/xcode/t2cstr.xcodeproj/project.pbxproj, c/public/lib/build/ttread/osx/xcode/ttread.xcodeproj/project.pbxproj, c/public/lib/build/tx_shared/osx/xcode/tx_shared.xcodeproj/project.pbxproj, c/public/lib/build/uforead/osx/xcode/uforead.xcodeproj/project.pbxproj, c/public/lib/build/ufowrite/osx/xcode/ufowrite.xcodeproj/project.pbxproj, c/public/lib/build/varread/osx/xcode/varread.xcodeproj/project.pbxproj, c/public/lib/source/dynarr/dynarr.c, c/public/lib/source/uforead/uforead.c
The primary change in this PR is the addition of code to explicitly set new memory to zero when a dynamic array grows. This fixes a bug in `mergefonts` in which it would fail on a semi-random glyph with the message `mergefonts: (cfr) charstring parse error`.
In the process of tracking down that problem, I fixed a couple of other memory issues which reported by Xcode's memory diagnostics. One was memory that was getting freed before it was used. The other was an incorrect variable type that was causing a pointer alignment issue.
Along the way, I also updated several Xcode project files semi-automatically with the changes recommended by Xcode 10.2.1.
=> [mergefonts] explicitly zero out new dynamic array memory

docs/OpenTypeFeatureFileSpecification.md
Above, the length limit is also 63 for glyph names, so this isn't needed.
=> Glyph name length is same as Named glyph class length

python/afdko/makeinstancesufo.py, tests/convertfonttocid_test.py, tests/makeinstancesufo_data/input/badsource.designspace, tests/makeinstancesufo_data/input/noinstances.designspace, tests/makeinstancesufo_test.py, tests/makeotf_test.py, tests/otc2otf_test.py
- replace `readDesignSpaceFile` with `filterDesignspaceInstances` , use fontTools.designspaceLib
- add `validateDesignspaceFile` to check for module-specific conditions
- add tests to exercise ^^
- updated `setup_module` in several test modules to remove stale/leftover temp output dir
- modified how exceptions/etc. are handled for `import` case vs CLI/`subprocess` case
- additional items flagged by @miguelsousa
=> [makeinstancesufo] update instance filtering, improve tests

python/afdko/buildmasterotfs.py, tests/buildmasterotfs_data/input/bad_dsfile/TestVF.designspace, tests/buildmasterotfs_test.py
- bump version to 1.9.1
- use fontTools.designspaceLib/remove xml.etree
- add designspace file validation
- add test to exercise validation
- improve error/returncode for `import` vs CLI/subprocess use
=> [buildmasterotfs] designspace file updates

python/afdko/makeotf.py
In macOS 10.15 it is not possible to reach temporary files in the `/var` folder using relative paths, hence this change in `makeotf.py` to using absolute paths for temporary files. See #828 for more details.
fixes #828
=> [makeotf] use absolute paths for temp files

.circleci/check_source_code.sh
Without "set -e" the exit code is the code of the last command ran by the shell script; if the last command is successful any previous errors are ignored and the shell script exits successfully (i.e. zero exit code).
Fixes #834
=> [ci] Fix flake8 step

.flake8, python/afdko/makeotf.py, tests/spot_test.py
Attempted update of flake8, but ended up reverting to ignoring W504 because enabling all warnings results in conflicting W503; the two are directly contradictory. In the process of this update, attempted to confirm that .flake8 file is actually being used for all flake8 tests in CircleCI (confirmed by tests). One test file and one other file had E501 errors that were fixed as a result.
=> [ci] flake8 config & file update

python/afdko/autohint.py, python/afdko/beztools.py, python/afdko/comparefamily.py, python/afdko/convertfonttocid.py, python/afdko/fdkutils.py, python/afdko/makeinstancesufo.py, python/afdko/makeotf.py, python/afdko/otc2otf.py, python/afdko/otf2otc.py, python/afdko/otfpdf.py, python/afdko/pdfdoc.py, python/afdko/pdfutils.py, python/afdko/proofpdf.py, python/afdko/stemhist.py, python/afdko/ttfcomponentizer.py, python/afdko/ttfpdf.py, python/afdko/ttxn.py, python/afdko/ufotools.py, tests/differ.py, tests/otc2otf_test.py, tests/otf2otc_test.py
- numerous modules
- also simplified `fdkutils.py` routines that do shell output (see [#847](https://github.com/adobe-type-tools/afdko/issues/847))
=> [python] drop use of fontTools.misc.py23

python/afdko/ufotools.py
`if not XXXXXX` construct raises a FutureWarning, originating in `lxml`. Now does an explicit check for `None`-ness. Closes #854.
=> [ufotools] avoid FutureWarning

python/afdko/otf2ttf.py, tests/otf2ttf_data/expected_output/kanjicid.ttx
@kenlunde pointed out that it shouldn't be present in TTFs
https://docs.microsoft.com/en-us/typography/opentype/spec/vorg
=> [otf2ttf] Remove VORG table

c/sfntedit/source/main.c
* fixed malloc for sourcepath to be large enough to include null terminator
* initialized an uninitialized variable
* removed a superfluous initialization
* removed an incorrect line of code
* removed a superfluous pointer check for a static array
=> [sfntedit] fix buffer size and other issues found in static analysis

c/makeotf/makeotf_lib/source/cffread/cffread.c, c/makeotf/makeotf_lib/source/hotconv/hot.c, c/makeotf/makeotf_lib/source/hotconv/name.c, c/makeotf/makeotf_lib/source/pstoken/pstoken.c, c/makeotf/makeotf_lib/source/typecomp/recode.c, c/makeotf/makeotf_lib/source/typecomp/tc.c, c/makeotf/source/cbpriv.c, c/makeotf/source/fcdb.c
`cffread.c`
* added iteration count limit to `flatten()`
* added recursion depth limit to `flatten()`
`hot.c`
* added check to ensure `message` buffer size not exceeded
`name.c`
* replaced a couple of `sprintf()` calls with `snprintf()`
`pstoken.c`
* cast indices for `class[]` to `uint8_t` to prevent negative index with `c >= 0x80`
* cast indices for `digits[]` to `uint8_t` to prevent negative index with `c >= 0x80`
`recode.c`
* check if there are any operators before processing them in `recodePath()`
`tc.c`
* check `FontName` for `NULL` pointer before taking length of it in `fillInitialSizes()`
`cbpriv.c`
* replaced a couple of `vsprintf()` calls with `vsnprintf()`
`fcdb.c`
* added a boundary check before a call to `strncpy()` in `buildDefaultRec()`
* replaced a call to `strcpy()` with a …
=> [makeotfexe] added some boundary checks and iteration & recursion limits

c/public/lib/source/uforead/uforead.c
(so reference to it doesn't go out of scope)
=> [uforead] make subs_name static

c/public/lib/source/absfont/absfont.c, c/public/lib/source/absfont/absfont_compare.c, c/public/lib/source/absfont/absfont_desc.c, c/public/lib/source/absfont/absfont_draw.c, c/public/lib/source/absfont/absfont_dump.c, c/public/lib/source/absfont/absfont_path.c
absfont.c:
* changed a variable type for consistency
absfont_compare.c:
* reduced the scope of a couple of variables
absfont_desc.c:
* removed superfluous code
absfont_draw.c:
* reduced the scope of a variable
* removed superfluous code
* moved `sizeof()` into `SPRINTF_S` calls to prevent unused variable warnings
absfont_dump.c:
* reduced the scope of a variable
* moved `sizeof()` into `SPRINTF_S` calls to prevent unused variable warnings
absfont_path.c:
* reduced the scope of several variables
* removed superfluous code
=> [absfont] cleaned up some Xcode & cppcheck warnings

c/sfntedit/build/osx/xcode/sfntedit.xcodeproj/project.pbxproj, c/sfntedit/source/Efile.c, c/sfntedit/source/Efile.h, c/sfntedit/source/Esys.c, c/sfntedit/source/main.c
`project.pbxproj`:
* updated automatically per Xcode's recommendations
`Efile.c`/`Efile.h`:
* `fileOpenWrite()` -- use `STRLCPY` instead of `strcpy`
* `fileReadN()` -- changed return type to `size_t`
* `fileWriteN()` -- changed return type to `size_t`
`Esys.c`:
* `sysFileLen()` -- check return values of `ftell` and `fseek`
* `sysOpenSearchpath()` -- close current file before opening a new one
`main.c`:
* `parseTagList()` -- changed `i` and `taglen` to `size_t`
* `parseArgs()`, `sfntCopy()`, & `main()` -- use `STRLCPY` instead of `strcpy`
Note:
* Added a macro `STRLCPY` that emulates `strlcpy` (since `strlcpy` is not portable).
=> [sfntedit] more fixes for issues found in static analysis

c/mergefonts/source/mergeFonts.c, c/public/lib/api/absfont.h, c/public/lib/api/cffread.h, c/public/lib/api/cffwrite.h, c/public/lib/api/dynarr.h, c/public/lib/api/pstoken.h, c/public/lib/api/sfntread.h, c/public/lib/api/svgwrite.h, c/public/lib/api/svread.h, c/public/lib/api/t1cstr.h, c/public/lib/api/t1read.h, c/public/lib/api/t1write.h, c/public/lib/api/t2cstr.h, c/public/lib/api/uforead.h, c/public/lib/api/varread.h, c/rotatefont/source/rotateFont.c, c/tx/source/tx.c
* incremented versions on changed C modules
* set `tx`, `mergefonts`, & `rotatefont` versions to have same version as each other due to shared code changes
* also fixed typo in `uforead.h`
=> bumped versions to reflect recent changes

c/makeotf/makeotf_lib/source/typecomp/subr.c, c/makeotf/makeotf_lib/source/typecomp/subr.h
=> [makeotfexe] port tx subroutinizer to makeotfexe

c/public/lib/source/ttread/ttread.c
(also reduced GLYF_MAX_COMPONENT_DEPTH)
=> [tx] added range check for Mac Roman encodings in ttread

.appveyor.yml
* Drops the dependency on **cibuildwheel**
* The tests now only run on untagged commits
=> Appveyor setup updates

.travis.yml
* Drops the dependency on **cibuildwheel**
* The tests now only run on untagged commits
=> Travis (macOS) setup updates

.travis.yml
The tests now only run on untagged commits.
Keeping the dependency on **cibuildwheel** for now.
=> Travis (Linux) setup updates

python/afdko/comparefamily.py
This function depends on tx's bc mode, which has never been available since the codebase went open source 🤦‍♂️
=> [comparefamily] Disable getItalicAngle function

c/mergefonts/build/osx/xcode/mergeFonts.xcodeproj/project.pbxproj, c/rotatefont/build/osx/xcode/rotateFont.xcodeproj/project.pbxproj, c/tx/build/osx/xcode/tx.xcodeproj/project.pbxproj
The header files were in the header search path, so the build worked, but the file icons in the Xcode IDE sidebar had dead links and were greyed out. This commit fixes that.
=> fix Xcode paths to header files in tx_shared

c/public/lib/source/tx_shared/tx_shared.c
* check for empty varRegionInfo in dumpCstr (like we already do in dcf_setNumRegions)
* check for invalid offSize in dumpINDEX
* check for stack underflow wth blend and vsindex in dumpCstr
=> [tx] check for various issues in dumpCstr and dumpINDEX

c/public/lib/source/tx_shared/tx_shared.c
* pop value off top of stack instead of pulling from bottom of stack
* check that vsindex value is within varRegionInfo array
=> [tx] improve handling of vsindex in dumpCstr

c/public/lib/source/cffwrite/cffwrite_dict.c
(Note that `STRCPY_S` is currently mapped to `strcpy` on mac, so the size parameter is not used there.)
=> [tx] allocate byte for null terminator when copying PostScript strings

c/public/lib/source/t2cstr/t2cstr.c
(instead of a mix of `h->aux->flags & T2C_IS_CFF2` and `h->flags & IS_CFF2`)
=> [tx] consistently use `h->flags & IS_CFF2` in t2cstr.c

c/public/lib/source/absfont/absfont_dump.c, tests/tx_data/expected_output/pr905.dump, tests/tx_test.py
This is related to:
* PR #905
* PR #908
=> [tx] fix handling of missing glyph names with the dump option

python/afdko/makeotf.py
This fixes two test failures in macOS 10.15 (Catalina) due to its prohibition of relative paths to the `/var` folder.
See also #828 and #838.
=> [makeotf] use absolute path to features file in updateFontRevision

python/afdko/pdflib/fontpdf.py
- investigation of LGTM/Semmle-reported "unused loop variable" issue led to removal of some (but not all) uses of `eval` in fontpdf.py
- there's still a lot more in there but I'm ignoring them for now
=> [fontpdf] fix loop variable issue

requirements.txt, setup.py
Strict pinning with `==` in AFDKO's `requirements.txt` can result in downgrades to packages that are shared by other co-installed projects. Use of `>=` enforces only the minimum version specified and allows later versions.
Closes #408 .
=> [requirements] relax pinning

docs/OpenTypeFeatureFileSpecification.md
the wording preceding this example refers to positioning a mark over a base glyph, so the keyword shoud be `position base` not just `position`.
=> [fea-spec] fix example n.4 in chapter 6.h.iii

c/mergefonts/source/mergeFonts.c, tests/mergefonts_data/input/camelCase/alias1.txt, tests/mergefonts_data/input/camelCase/alias2.txt, tests/mergefonts_data/input/camelCase/alias3.txt, tests/mergefonts_test.py
(for use with old glyph alias files that predate the name change)
fixes #1002
=> [mergefonts] allow use of camelCase "mergeFonts" in glyph alias files

python/afdko/autohint.py, python/afdko/stemhist.py
- add FutureWarnings to autohint.py and stemhist.py. Settled on using FutureWarning instead of DeprecationWarning so that it is displayed for all use cases (DeprecationWarning is hidden for some cases).
=> [autohint][stemhist] add FutureWarnings

docs/OpenTypeFeatureFileSpecification.md
* highlight keywords
* replace keywords with plain English and vice versa according to sense (e.g. `languageSystem` vs. “language system”)
* specify the language of code blocks where it was missing
* fix the formatting of the list in 2.g.i
* fix the link at the end of 4.b.i
* fix typos and grammatical mistakes
=> [fea spec] Improve formatting and grammar

python/afdko/pdflib/fontpdf.py, python/afdko/pdflib/otfpdf.py, tests/proofpdf_test.py
- explicitly convert `map` results to `list` in `fontpdf.makeFontSetPDF`
- add `__lt__` method to `otfpdf.txPDFFont` to make it sortable in ^^
- add simple test case for `fontsetplot`
closes #1034
=> Fix bug in fontpdf.py (map/list discrepancy)

tests/tx_test.py
Extend `PFA_SKIP` to include "%%Copyright:" so tests don't fail when attempting to compare to controls (we had a number of tx tests that started failing after 1/1/2020 against controls generated in 2019).
=> [tests] update tx_test.py

c/makeotf/makeotf_lib/source/hotconv/otl.c, tests/makeotfexe_data/expected_output/bug1017.GSUB.txt, tests/makeotfexe_data/input/bug1017/feat.fea
Fixed bug where a bad font built when feature file has multiple languagesystems and feature parameters #1080
Updated test file to fail the build tests with in versions of makeotf with this bug, and to pass in versions without this bug, by changing from one to three language system statements, and updating the expected ttx file.
=> [makeotfexe] Bad font built when feature file has feature parameters, issue 1080

.prospector.yaml, requirements.txt
- removed `.prospector.yaml` (Codacy file; no longer used)
- updated requirements.txt to latest, except `ufoProcessor` which seems to have some conflicts with `mutatorMath` (our makeinstancesufo test with anisotropic.ufo fails with latest ufoProcessor).
=> [requirements] update dependencies, clean up unused file

python/afdko/pdflib/fontpdf.py
update pdflib/fontpdf.py to address crash
closes #1092
=> [waterfallplot] fix crash

python/afdko/buildcff2vf.py
- updated to catch (and generate) `fontTools.varLib.cff.VarLibCFFPointTypeMergeError` instead of old `MergeTypeError`
- removed redefinition of `MergeTypeError`
closes https://github.com/adobe-type-tools/afdko/issues/1088
=> [buildcff2fv] update to new fontTools exceptions

docs/OpenTypeFeatureFileSpecification.md
Replaced incorrect `sub s s by germandbls` for latn/DEU with `c_h` & `c_k` for §4.h Example 2 (these are taken from Example 1 of that section for latn/DEU)
Closes #1106
=> [spec] Replace invalid example in Feature File spec [skip ci]

c/makeotf/makeotf_lib/api/hotconv.h, c/makeotf/makeotf_lib/source/typecomp/recode.c
- in `sizeFDWidths`, initialize `minsize` (int) to `INT_MAX` instead of `SHRT_MAX` to avoid potential undesired behavior in the case of `totsize` being larger than `SHRT_MAX` (which can apparently happen, see #1108)
- increment `HOT_VERSION` to 1.0.113
Closes #1108
=> [makeotf] avoid potential issue in recode.c

c/makeotf/makeotf_lib/source/cffread/cffread.c, c/public/lib/source/t1cstr/t1cstr.c, c/spot/source/t13supp.c
fixes a fatal arithmetic exception reported by @hardik05
=> prevent modulo zero when processing roll operator

c/makeotf/makeotf_lib/source/typecomp/dict.h
fixes an issue identified by LGTM
=> add missing prototype for dictSaveNumberAsShortInt

c/spot/source/CFF_.c, c/spot/source/glyf.c
(this fixes a crash that would occur with very long file paths)
=> [spot] increase workstr buffer size and use snprintf to prevent overflow

c/public/lib/source/absfont/absfont.c, c/public/lib/source/ttread/ttread.c
When building an afdko package on the openSUSE build service
many tests failed. After some investigation I compared the workflow
in parallel debugging sessions inside the build service and a
regular system (where they didn't fail). I noticed the reason
of the failing is that afdko uses some variables that were not
initialized so on systems where memory is automatically set to 0
they work fine, but this is not safe in general (and cannot
be guaranteed), so it's better to initialize the variables.
=> Initialize variables before use

python/afdko/otf2ttf.py, requirements.txt
The code was integrated into FontTools in version 4.7.0
https://github.com/fonttools/fonttools/releases/tag/4.7.0
=> Replace dependency on standalone cu2qu package

c/makeotf/makeotf_lib/source/hotconv/map.c
Change comment regarding the setting of CodePageRange bits to reflect the actual behavior of the code.
Closes #1156
=> [makeotf] update comment [skip ci]

python/afdko/checkoutlinesufo.py, python/afdko/ufotools.py, tests/checkoutlinesufo_data/expected_output/bug790.ufo/glyphs.com.adobe.type.processedglyphs/scedilla.glif, tests/makeinstancesufo_data/expected_output/light.ufo/glyphs.com.adobe.type.processedglyphs/y.glif, tests/makeinstancesufo_data/expected_output/light.ufo/glyphs.com.adobe.type.processedglyphs/yacute.glif, tests/makeinstancesufo_data/expected_output/light.ufo/glyphs.com.adobe.type.processedglyphs/ydieresis.glif, tests/makeinstancesufo_data/expected_output/light.ufo/glyphs.com.adobe.type.processedglyphs/ytilde.glif, tests/makeinstancesufo_data/expected_output/ufo3semibold.ufo/glyphs.com.adobe.type.processedglyphs/a.glif, tests/makeinstancesufo_data/expected_output/ufo3semibold.ufo/glyphs.com.adobe.type.processedglyphs/aacute.glif, tests/makeinstancesufo_data/expected_output/ufo3semibold.ufo/glyphs.com.adobe.type.processedglyphs/adieresis.glif, tests/makeinstancesufo_data/expected_output/ufo3semibold.ufo/glyphs.com.adobe.type.processedglyphs/atilde.glif
- modify check for contour starts (base contour indices on original glyph, not fixed glyph)
- update `thresholdAttrGlyph` method: don't try to "fix" smooth points, use threshold of 0.5 **N.B. this change causes changes to test data** w/r/t smoothed points
- update to use `ufoVersionFormatTuple` consistently throughout module
- improve messaging for KeyError and failed assertion in overlap removal/contour renumbering scheme
=> [checkoutlinesufo, ufotools] improve overlap removal, error messages

c/makeotf/makeotf_lib/build/hotpccts/featgram.g, c/makeotf/makeotf_lib/source/hotconv/featgram.c, tests/makeotfexe_data/expected_output/spec/9i-1.ttx, tests/makeotfexe_data/expected_output/spec/9i-2.ttx, tests/makeotfexe_data/expected_output/spec/9i-20.ttx, tests/makeotfexe_data/expected_output/spec/9i-21.ttx, tests/makeotfexe_data/expected_output/spec/9i-25.ttx, tests/makeotfexe_data/expected_output/spec/9i-4.ttx
Fixed the flag values for  `OlderSiblingFontAttribute` and `ElidableAxisValueName` because they were reversed.
=> Fix reversed STAT flags

c/public/lib/api/pstoken.h, c/public/lib/api/svread.h, c/public/lib/api/t1read.h, c/public/lib/source/pstoken/pstoken.c, c/public/lib/source/svread/svread.c, c/public/lib/source/t1read/t1read.c
Updates several components of `tx`:
- in pstoken.c: fixed an issue that could result in heap use-after-free in a malformed file
- in svread.c: fixed an issue that could result in stack buffer overflow in a malformed file
- in t1read.c: fixed an issue that could result in stack use-after-scope in a malformed file
Version numbers are updated for all components.
=> [tx] improve robustness of components

c/makeotf/makeotf_lib/api/hotconv.h, c/makeotf/makeotf_lib/build/hotpccts/featgram.g, c/makeotf/makeotf_lib/source/hotconv/STAT.c, c/makeotf/makeotf_lib/source/hotconv/featgram.c, c/makeotf/makeotf_lib/source/hotconv/name.c, c/makeotf/source/main.c, docs/MakeOTFUserGuide.md, docs/OpenTypeFeatureFileSpecification.md, python/afdko/makeotf.py, tests/makeotfexe_data/expected_output/fealib/bug1178.ttx, tests/makeotfexe_data/expected_output/spec/9i-2.ttx, tests/makeotfexe_data/expected_output/spec/9i-21.ttx, tests/makeotfexe_data/expected_output/spec/9i-22.ttx, tests/makeotfexe_data/expected_output/spec/9i-25.ttx, tests/makeotfexe_data/expected_output/spec/9i-4.ttx, tests/makeotfexe_data/expected_output/spec/9i-5.ttx, tests/makeotfexe_data/expected_output/spec/9i-6.ttx, tests/makeotfexe_data/input/fealib/bug1178.fea, tests/makeotfexe_data/input/fealib/incomplete_glyph_range.bad.fea, tests/makeotfexe_data/input/fealib/name_after_STAT.bad.fea, tests/makeotfexe_data/input/spec/9i-21.fea, tests/makeotfexe_test.py
Add `[STAT]` to STAT table messages
Update STAT handling to write version 1.2 table only if there are Format 4 Axis value tables
Warn if unregistered axis tags are not uppercase
Warn if Format 2 default value is not in min-max range
Fail if DesignAxis tag has already been defined
Fail if Axis Value Table of the same format has already been defined with the same values
Add `[name]` to name table messages
Warn when overwriting existing nameid
Fail if GSUB or STAT are defined before name table and name table sets nameids above 255. Fixes #1178 
Docs:
Clarify use of Unicode values in column 3 of GlyphOrderAndAliasDB. Fixes #1177
=> makeotfexe STAT/name table fixes

c/makeotf/makeotf_lib/build/hotpccts/featgram.g, c/makeotf/makeotf_lib/source/hotconv/featgram.c, c/makeotf/makeotf_lib/source/typecomp/recode.c
This PR fixes two issues found by running `makeotfexe_test.py` with `AddressSanitizer` (ASAN):
* `heap-use-after-free` in `recode.c`
* `stack-buffer-overflow` in `featgram.c`
=> [makeotfexe] fix stack-buffer-overflow and heap-use-after-free

c/makeotf/makeotf_lib/source/hotconv/GPOS.c
This PR fixes a `heap-use-after-free` in `GPOS.c` found by running `makeotfexe_test.py` with `AddressSanitizer` (ASAN).
=> [makeotfexe] fix heap-use-after-free in GPOS.c

c/mergefonts/source/mergeFonts.c
This PR fixes a `stack-buffer-overflow` in `mergeFonts.c` found by running `mergefonts_test.py` with `AddressSanitizer` (ASAN).
=> [mergefonts] fix stack-buffer-overflow

c/spot/source/tto.c
This PR fixes a `heap-buffer-overflow` in `tto.c` found by running `spot_test.py` with `AddressSanitizer` (ASAN).
=> [spot] fix heap-buffer-overflow

c/public/lib/api/varread.h, c/public/lib/source/varread/varread.c
Added an upper limit check on the size of `hmtx` to the existing lower limit check. This check limits the memory impact of a font with a malformed `hmtx` table.
=> [tx] check upper limit of hmtx size

c/public/lib/api/cffread.h, c/public/lib/source/cffread/cffread.c
- amend previous fix to 1/2 of previous limit (the `malloc` in question used *8, not *4)
- bump `cffread` version #
=> [tx] update limit to avoid large memory allocations

docs/OpenTypeFeatureFileSpecification.md
Update spec with correct description of `value` for STAT location format A.
Closes #1190
=> [docs] correct STAT location value description [skip ci]

python/afdko/ttfcomponentizer.py, tests/ttfcomponentizer_test.py
Update `ttfcomponentizer` and related tests:
- add a warning when UFO lib.plist `public.postscriptNames` key is present but empty
- add test to ensure warning is issued for this condition
Closes #1198
=> [ttfcomponentizer] add warning for empty psnames

.circleci/check_source_code.sh, .flake8, .github/workflows/testpythonpackage.yml, python/afdko/checkoutlinesufo.py, python/afdko/convertfonttocid.py, python/afdko/makeotf.py, python/afdko/ttfcomponentizer.py, python/afdko/ttxn.py, python/afdko/ufotools.py, requirements-dev.txt, tests/runner.py
Add `flake8-bugbear` checks
- add flake8-bugbear to requirements-dev.txt
- enable flake8-bugbear checks in .flake8 config
- add exceptions to .flake8 config
- fix Python modules that had flake8-bugbear violations & update versions
- tweak GitHub Test action to use .flake8 config & other minor changes
- tweak CircleCI flake8 checks (pick up exceptions via config file)
=> [tests] add flake8-bugbear

tests/makeotf_test.py
Work around a minor path discrepancy in a few of the `makeotf` tests when the `pytest` command is initiated from filesystem root (cibuildwheel in GitHub Action).
=> [tests] force working dir in makeotf_test.py

python/afdko/makeinstancesufo.py
Make designspace attributes all lowercase, corresponding to the specification here: https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib\#attributes-9
The spec itself seems to be inconsistent in attribute casing.
Tested with a `<designspace format="3">` file.
Resolves #1211 .
=> Make designspace attributes lowercase.

README.md
=> clarify use of Python 3 and pip3 in README.md

docs/OpenTypeFeatureFileSpecification.md
The current description of glyph name ranges is unclear in a few critical points.
Fixes #1222 
This is a proposed enhancement to the feature file spec documentation. The current
wording in section 2.g.i regarding ranges is unclear. At several points, a reader can be
left scratching their heads wondering what was meant. This is intended to provide
greater clarity in that section.
- [X ] I have followed the [Contribution Guidelines](https://github.com/adobe-type-tools/afdko/blob/develop/CONTRIBUTING.md)
=> Clarify glyph name ranges (2.g.i)

python/afdko/makeinstancesufo.py
This really fixes #1211.
The attributes stay camelCase, only the error message is reported in all-lowercase.
=> Revert #1212, lowercase error message only

tests/tx_test.py
This change is intended to fix this issue:
```
--- /home/runner/work/afdko/afdko/tests/tx_data/expected_output/bug1218.pdf
+++ /tmp/tmppqy3jwgv/bug1218.pdf
@@ -36,5 +36,5 @@
(Em:  4000 units)'
-498.50 30.00 Td
+500.30 30.00 Td
-16.00 0.00 Td
+14.10 0.00 Td
```
Here's the relevant section of the PDF, for context:
```
(Filename:  bug1218.otf)'
(FontName:  UPM-Regular)'
(Em:  4000 units)'
500.30 30.00 Td
(Date:  02 Oct 20)'
14.10 0.00 Td
(Time:  13:49)'
```
=> [tx_test.py] change skip regex for bug1218 to skip date & time metrics

python/afdko/checkoutlinesufo.py
This is a fix for the following issue identified by LGTM:
```
Nested for statement uses loop variable 'point' of enclosing for statement.
```
(I created this PR mainly to check if our LGTM configuration is still working now that GitHub's officially released "code scanning".)
=> [checkoutlinesufo] fix nested loop variable

docs/MakeOTFUserGuide.md
[this is a re-issue of #1237 which was on the wrong branch]
I got tripped up with a Python exception because I had written my GlyphOrderAndAliasDB file with comma separators rather than space separators. I've now added some documentation about that.
=> Describe the tab separator format of GlyphOrderAndAliasDB [skip ci]

docs/OpenTypeFeatureFileSpecification.md
Tiny fix in feature file specification docs.
=> Fix typo in docs

.github/workflows/asan.yml, .github/workflows/build_wheels.yml, .github/workflows/run_cvg.yml, .github/workflows/testpythonpackage.yml, c/makeotf/makeotf_lib/api/hotconv.h, c/makeotf/makeotf_lib/build/hotpccts/featgram.g, c/makeotf/makeotf_lib/source/hotconv/featerr.c, c/makeotf/makeotf_lib/source/hotconv/featgram.c, c/makeotf/makeotf_lib/source/hotconv/featpars.dlg, c/makeotf/makeotf_lib/source/hotconv/featscan.c, c/makeotf/source/main.c, python/afdko/makeotf.py
Several major and minor updates relating to CI/automation:
- set the GitHub Actions "build wheels" workflow to publish wheels on tag pushes (not part of this PR but related: disabled Travis CI and AppVeyor builds which did this previously)
- added a scheduled (cron) run of the AFDKO Test Suite GitHub Actions workflow
- updated AFDKO Test Suite GitHub Action to use MSBuild v1.0.2 to avoid use of a deprecated action
- added `workflow_dispatch` event to all GitHub Actions workflows
- fixed an issue in `makeotf` sources that caused a failure in Azure Pipelines Mac build
- updated ["CI Matrix"](https://github.com/adobe-type-tools/afdko/wiki/CI-Matrix) wiki page (not part of this PR but related)
=> CI Updates

python/afdko/checkoutlinesufo.py, tests/checkoutlinesufo_test.py
- updated checkoutlinesufo to accept -o/--output-file option, a path specifying an output file. When this option is specified, the input file will first be copied to the specified output file path, and successive operations will occur on that path.
- added test case (uses existing input/expected data)
closes #1242
=> [checkoutlinesufo] implement -o (output file) option

requirements.txt
[`mutatorMath`](https://github.com/LettError/MutatorMath) is a dependency of [`ufoProcessor`](https://github.com/LettError/ufoProcessor) but it's not a direct dependency of **afdko**.
=> [requirements] remove mutatorMath, update fontTools

setup.py
Explicitly list `afdko.pdflib` in setup `packages=`. Thanks @erniemarch for catching this!
Closes #1277
=> [packaging] update setup.py

python/afdko/buildcff2vf.py
Same as #1282 – but on a branch (to run the tests).
This fixes #1281 , but I’d like @punchcutter to have a look – it could be that my fix is too simple.
=> Do not assume presence of STAT.AxisValueArray

docs/MakeOTFUserGuide.md
- consistent md formatting
- remove empty table row
- add code fences
=> (docs) update README.md

python/afdko/checkoutlinesufo.py, tests/checkoutlinesufo_data/expected_output/contour-restore-ignored.ufo/data/com.adobe.type.processedHashMap, tests/checkoutlinesufo_data/expected_output/contour-restore-ignored.ufo/fontinfo.plist, tests/checkoutlinesufo_data/expected_output/contour-restore-ignored.ufo/glyphs.com.adobe.type.processedglyphs/cid51107.glif, tests/checkoutlinesufo_data/expected_output/contour-restore-ignored.ufo/glyphs.com.adobe.type.processedglyphs/contents.plist, tests/checkoutlinesufo_data/expected_output/contour-restore-ignored.ufo/glyphs/cid51107.glif, tests/checkoutlinesufo_data/expected_output/contour-restore-ignored.ufo/glyphs/contents.plist, tests/checkoutlinesufo_data/expected_output/contour-restore-ignored.ufo/layercontents.plist, tests/checkoutlinesufo_data/expected_output/contour-restore-ignored.ufo/lib.plist, tests/checkoutlinesufo_data/expected_output/contour-restore-ignored.ufo/metainfo.plist, tests/checkoutlinesufo_data/input/contour-restore.ufo/fontinfo.plist, tests/checkoutlinesufo_data/input/contour-restore.ufo/glyphs/cid51107.glif, tests/checkoutlinesufo_data/input/contour-restore.ufo/glyphs/contents.plist, tests/checkoutlinesufo_data/input/contour-restore.ufo/layercontents.plist, tests/checkoutlinesufo_data/input/contour-restore.ufo/lib.plist, tests/checkoutlinesufo_data/input/contour-restore.ufo/metainfo.plist, tests/checkoutlinesufo_test.py
In some situations we have no use for attempting to restore the contour order so force it to be skipped with the `--ignore-contour-order` flag.
=> Add ignore-contour-order flag to checkoutlinesufo

python/afdko/makeinstancesufo.py
This is part of addressing #1161 by adding multiprocessing
=> [makeinstancesufo.py] Adding multiprocessing to run

docs/OpenTypeFeatureFileSpecification.md
See #1234 
Note that this is *described* as a 5.a single substitution - because the feature syntax is "`sub <something> by <something else>`" - even though (as an implementation detail) it compiles to a multiple substitution.
=> Add "sub A by NULL" to specification

python/afdko/checkoutlinesufo.py, tests/checkoutlinesufo_data/expected_output/restore_contour_order_warned.ufo/data/com.adobe.type.processedHashMap, tests/checkoutlinesufo_data/expected_output/restore_contour_order_warned.ufo/fontinfo.plist, tests/checkoutlinesufo_data/expected_output/restore_contour_order_warned.ufo/glyphs.com.adobe.type.processedglyphs/cid51107.glif, tests/checkoutlinesufo_data/expected_output/restore_contour_order_warned.ufo/glyphs.com.adobe.type.processedglyphs/contents.plist, tests/checkoutlinesufo_data/expected_output/restore_contour_order_warned.ufo/glyphs/cid51107.glif, tests/checkoutlinesufo_data/expected_output/restore_contour_order_warned.ufo/glyphs/contents.plist, tests/checkoutlinesufo_data/expected_output/restore_contour_order_warned.ufo/layercontents.plist, tests/checkoutlinesufo_data/expected_output/restore_contour_order_warned.ufo/lib.plist, tests/checkoutlinesufo_data/expected_output/restore_contour_order_warned.ufo/metainfo.plist, tests/checkoutlinesufo_test.py
=> [checkoutlinesufo] Fix restore_contour_order fail

requirements.txt
bump `psautohint` requirement to latest release (v2.3.0)
=> [requirements] bump psautohint to v2.3.0

python/afdko/makeotf.py
According to the https://github.com/fonttools/fonttools/issues/2178#issuecomment-774528018, it makes sure script doesn't fail on attempt to convert format 3 post table to format 2.
Fixes #1301
=> Make sure format 3 post table doesn't break makeotf

.github/workflows/run_cvg.yml, .github/workflows/testpythonpackage.yml
Remove checks for [skip ci] in commit messages in GitHub Actions workflow files, since GitHub now [performs this check at a higher level](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/).
Closes #1323
=> [ci] Update GitHub Actions workflow files [skip ci]

python/afdko/checkoutlinesufo.py
In a 65k font this made `checkoutlinesufo` spend 15% of the time sorting the list on each iteration.
=> Moved list sort out of loop to not waste time sorting.

docs/OpenTypeFeatureFileSpecification.md
The example 4 of section 6.h.iii starts with `mark sukun <anchor 0 0> @TOP_CLASS;` but that should be `markClass sukun <anchor 0 0> @TOP_CLASS;`
N/A
=> Spec 6.4.iii: 'markClass' instead of 'mark' in example 4

c/makeotf/lib/hotconv/FeatCtx.cpp, c/makeotf/lib/hotconv/FeatCtx.h, c/makeotf/lib/hotconv/FeatVisitor.cpp, c/makeotf/lib/hotconv/FeatVisitor.h
I had thought that `std::string` objects retrieved from the parser tree are valid for the lifetime of the tree but there seems to be some other smart-pointer stuff going on. In most cases there is no difference (because strings are either used in the function where they're retrieved or passed "down") but FeatCtx::tokstr() needs to be changed to store the string.
I also changed the "reference token" for feature blocks to the start tag so that the error message makes sense. (That would have been a better choice to begin with anyway.)
=> Copy token string when using FeatCtx::tokstr()

.github/workflows/build_wheels.yml
Related to #1376 , #1375 , #1374 
Attempting to fix `sh: apt-get: command not found`, which may be because of docker linux images using `yum` as a package manager.
=> [build_wheels.yml] Try yum instead of apt-get for linux

python/afdko/makeinstancesufo.py, requirements.txt, tests/makeinstancesufo_data/expected_output/Dummy-ExtraMinus.ufo/fontinfo.plist, tests/makeinstancesufo_data/expected_output/bold.ufo/fontinfo.plist, tests/makeinstancesufo_data/expected_output/regular.ufo/fontinfo.plist, tests/makeinstancesufo_data/expected_output/regular1.ufo/fontinfo.plist, tests/makeinstancesufo_data/expected_output/semibold.ufo/fontinfo.plist, tests/makeinstancesufo_data/expected_output/ufo2.ufo/fontinfo.plist
This fixes test values for new, more accurate `italicAngle` values produced by the new fontMath 0.8.1 update.
This also fixes a bug in `makeinstancesufo` (not caught in tests until now) where `roundSelectedFontInfo(dFont.info)` was only called when the -r option was used (because it would have no-rounding _except_ for the values that need it) when they should always be rounded
=> makeinstancesufo fixes for fontMath 0.8.1 update

README.md, docs/FDK_Build_Notes.md
The Antlr 4 Cpp runtime adds a guid/uuid to some elements of its parsers. It can satisfy that dependency with built-in parts of macOS and Windows but on other OSes `libuuid` and its headers must be installed (it uses `pkg_check_modules(UUID REQUIRED uuid)` in `CMakeLists.txt` on Linux).
This is effectively another "build tools" requirement and will already be satisfied on many systems, but some users will need to install an extra package or, possibly in rare cases, install libuuid from source. This PR adds some documentation to that effect. There's also some doc cleanup here and there.
=> Add more detailed docs for building cmake-based AFDKO from source

.github/workflows/build_wheels.yml, .github/workflows/run_cvg.yml, .github/workflows/testpythonpackage.yml, .run_cpplint.sh, README.md, c/makeotf/lib/hotconv/hot.c, setup.py
Updates and improvements to dropping Python 3.6 and add Python 3.10 support:
- Update test workflow (run on Python 3.7, 3.8, 3.9, and 3.10 only, update cpplint run, colorize pytest log, test uninstall AFDKO)
- Update coverage workflow (make AFDKO installation & coverage upload separate steps)
- Update build_wheels workflow (use CIBW Action, only build Python 3.7-3.10 wheels, update tag-matching, remove "Use MSBuild" step)
- Other miscellaneous updates and improvements to GHA workflows
- Update README.md to indicate Python 3.7 minimum
=> Drop Python 3.6, add Python 3.10 support

README.md
- fix typo ("OpenSource" -> "Open Source")
- use fully-qualified URL to link to Apache 2.0 license on OSI site (relative link fails when README is viewed through PyPI)
- ~[ ] I have added **test code and data** to prove that my code functions correctly~
- ~[ ] I have verified that new and existing tests pass locally with my changes~
- ~[ ] I have performed a self-review of my own code~
- ~[ ] I have commented my code, particularly in hard-to-understand areas~
=> [skip ci] fix broken relative link in README

.github/workflows/run_cvg.yml
The last time C-code coverage results were reported was in June 1, 2021
https://codecov.io/gh/adobe-type-tools/afdko/tree/1523970f566cc6049a6fe543690837db94a1b61d
Coverage results in June 8, 2021
https://codecov.io/gh/adobe-type-tools/afdko/tree/01a35dacc9e8d1735b7f752f3232d38c34e6f843
Coverage results after this change
https://codecov.io/gh/adobe-type-tools/afdko/tree/3199a40373fafd0185a5ca4cc8cfc9d33a8084c3
=> Fix C-code coverage reporting

.github/workflows/build_wheels.yml, c/makeotf/lib/hotconv/FeatCtx.cpp, c/makeotf/lib/hotconv/FeatVisitor.h
With these changes the macOS arm64 wheel builds successfully.
- https://pypi.org/project/afdko/3.8.0a19/#files
- https://github.com/adobe-type-tools/afdko/releases/tag/3.8.0a19
=> Add macOS arm64 wheel

.github/workflows/build_wheels.yml
Builds `universal2` (`x86_64` & `arm64`) wheel instead of `arm64`-only wheel, for macOS.
https://pypi.org/project/afdko/3.8.0b0/#files
=> Build universal2 wheel instead of arm64

c/tx/source/tx.c
This adds initialization of the `fileStat` variable in `doFile`. Previously `fileStat` was accessed prior to initialization.
=> [tx] initialize variables in doFile

c/shared/include/pdfwrite.h, c/shared/source/pdfwrite/pdfwrite.c, c/tx/source/tx.c
Updates to pdfwrite.c to avoid an out-of-bounds read error with malformed input files in `tx -pdf` mode caused by an uninitialized `pdwCtx` structure. Version numbers for pdfwrite and tx were also updated.
=> [tx] Add safety initialization of pdwCtx structure in pdwNew

.github/workflows/build_wheels.yml, .github/workflows/run_cvg.yml, .github/workflows/testpythonpackage.yml
This is a temporary fix for installing utfcpp within ANTLR4 build. GitHub's protocol security improvement was made permanent today: https://github.blog/2021-09-01-improving-git-protocol-security-github/
The fix right now is running `git config --global url.https://github.com/.insteadOf git://github.com/` in the wheels before building the FDK. We had these commands in the wheels before, but were removed a few months ago.
The permanent fix for this will be upgrading to the latest ANTLR4.
=> git protocol security fix for utfcpp/antlr4

.github/workflows/build_wheels.yml
I think that we can run git config once in its own step before running everything else. 
[This example here](https://github.com/actions/checkout#push-a-commit-using-the-built-in-token) shows that it should work if uses and run are their own steps.
=> [build_wheels.yml] Run git config in its own step

c/shared/source/uforead/uforead.c
Fixing memory crashes found in OpenSUSE x86 VM and Mac (with address sanitizer). 
Each FDict in FDArray needed to be initialized after memory was allocated
=> [uforead.c] Fix Memory Crashes

docs/FDK_Build_Notes.md
I thought it may be nice to include links to Windows-specific build issues in the build doc as reference.
=> [FDK_Build_Notes.md] Add links to previously opened Windows build issues

docs/OpenTypeFeatureFileSpecification.md
Documentation-only fix: an unfortunate hard-wrap in docs/OpenTypeFeatureFileSpecification.md caused a line to begin with "0. ", unintentionally creating a numbered list in the rendered Markdown.
closes #1507
=> [skip-ci] [spec] [formatting-only] fix bad linebreak

c/makeotf/lib/hotconv/FeatCtx.cpp
The error-printing code first tries to use a 128 byte buffer for output and then resizes if that fails. This code was mistakenly assuming the va_list wasn't altered as part of the call. This PR makes a copy va_list in case it is needed. It also adds va_end calls that were mistakenly left out of the original PR. 
Closes #1504
=> Copy va_list for second use (and add va_end's to avoid leaking)

.github/workflows/build_wheels.yml
Attempting to fix pre-release fail where Windows cannot install libxml2 with these commands in the env (it needs to run ExternalProject_Add in cmake!). I think removing these commands should help, since the other wheels files (testpythonpackage.yml) build that way, but we'll have to test with another prerelease push
=> [build_wheels.yml] Remove env installation of libxml2 for Windows

c/makeotf/lib/typecomp/parse.c, c/makeotf/source/c_main.c, c/shared/source/t1read/t1read.c
I ran into some post-libxml2 commit compilation problems on Arch Linux, which
seem to be related to libxml2 header files pulling the `stdbool.h` header into some new contexts:
```
FAILED: c/shared/source/CMakeFiles/t1read.dir/t1read/t1read.c.o 
/usr/local/bin/cc -DANTLR4CPP_STATIC -I/usr/include/libxml2 -I/home/skef/src/afdko2/c/shared/source/../include -I/home/skef/src/afdko2/c/shared/source/../resource -O2 -g -DNDEBUG -MD -MT c/shared/source/CMakeFiles/t1read.dir/t1read/t1read.c.o -MF c/shared/source/CMakeFiles/t1read.dir/t1read/t1read.c.o.d -o c/shared/source/CMakeFiles/t1read.dir/t1read/t1read.c.o -c /home/skef/src/afdko2/c/shared/source/t1read/t1read.c
In file included from /usr/include/unicode/umachine.h:52,
from /usr/include/unicode/utypes.h:38,
from …
```
=> makeotf and shared: Fix some linux compile problems with "bool"

python/afdko/otf2ttf.py
#1421 introduced only an upper-limit but not a lower one. It causes errors in some cases.
This pr will fix the problem.
=> Ensure `poolCapacity` is at least 1

c/shared/source/uforead/uforead.c
I found this while debugging #1538, which looks like the problem was mostly solved for by the libxml2 changes in #1515 and #1523. The only remaining issue seems to be the following:
`currentiFD` is a variable used to track which font dict index is pointed to in the FDArray. This is used in UFO parsing of fontinfo.plist, as well as glyphs files (in that order). While parsing glyphs files, the `currentiFD` is changed to -1. `mergefonts` parses fontinfo.plist again after the glyphs files, which causes a memory leak in non-M1 and a fail in M1 Macs because `currentiFD` should start with 0 (this points to the initial font dictionary).
Since the test doesn't fail on non-M1 unless ASAN is enabled, I did not add a new test.
This is a temporary fix as I'll rewrite glyphs parsing when working on …
=> [uforead] Set currentiFD to 0

python/afdko/makeinstancesufo.py
The makeinstancesufo tests currently fail on single-processor systems due to requesting 0 cores for the multiprocessing pool. This bumps the count by one.
The motivation to leave one processor free is understandable. However, if the "organizing" thread isn't very active when the pool is running it seems fine to rely on the timesharing in the OS and just use all the cores.
=> Boost number of makeinstancesufo pool processors by one

python/afdko/agd.py, python/afdko/comparefamily.py
Replaces the two instances of "rU" with "r", as python now deals with newlines by default since Python 3.4. Fixes #1583
- [-] I have added **test code and data** to prove that my code functions correctly
- [-] I have commented my code, particularly in hard-to-understand areas
- [-] I have made corresponding changes to the documentation
=> Fixing the two instances of "rU"

c/shared/source/t2cstr/t2cstr.c
`handleBlend()` in shared/t2cstr.c "handles" flattening by adjusting values on the _stack_. Because it doesn't copy the `blendValues` into the `opEntry` in the flatten mode, you do wind up with `numBlends` equaling zero in that entry but you wind up with the _default_ in `value` rather than the blended value.
Perhaps `handleBlend()` should also adjust the `opEntry->value` in the flatten case, but I'm reluctant to do that because it seems like the value may be cross-referenced in other places. And while this would fix our stem calculation problems it appears that the curveto case is more complicated and would need additional work. 
Anyway, there's no real point to using the blend when we're flattening.
So instead this PR just avoids using the blends entirely when calling out downstream …
=> Use non-xxxVF paths in t2cstr when flattening and outputting CFF2

c/shared/source/cffwrite/cffwrite_t2cstr.c
The current version of this file stores stems in a union, with just a float for edge0 and edge1 in one case and a blend structure in the other. CFF2 uses the blend while CFF uses just the float. The blend `.value` happens to coincide with the float.
This sort of works but the model breaks down for non-blended stems in CFF2 output. It's better to just use the blend structure for all cases with hasBlend set to false if there's no blend data. That way CFF output can ignore everything but the "default" value and CFF2 output can correctly detect whether it needs to output a blend.
=> Always use blend for stem storage in cffwrite_t2cstr.c

c/shared/source/uforead/uforead.c
Also Fix ancient transform->isDefault logic error.
What it says on the tin.
=> Restore stack-like behavior of parseGLIF transform pointer

.github/workflows/build_wheels.yml
=> Force static link of libxml2 on both windows and linux

python/afdko/checkoutlinesufo.py
flake8 was failing on linux due to the stacklevel being a default of 1 in a checkoutlinesufo warning. Updating to fix flake8 failure.
~~- [ ] I have added **test code and data** to prove that my code functions correctly~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
=> flake8 fix

docs/CIDKeyedUFOGuide.md
Add guide for using new functionality in `tx` for CID-keyed UFOs.
=> CID-keyed UFO guide

.github/workflows/asan.yml, .github/workflows/testpythonpackage.yml, README.md, requirements-dev.txt, requirements.txt, setup.py
⚠️ Starting April 3, 2023, the AFDKO will require Python 3.8 or later. Due to our dependencies already dropping support and requiring Python 3.8 in their latest versions, we will also be dropping Python 3.7 support on April 3, 2023.
=> Drop Python 3.7

c/spot/sfnt_includes/sfnt_name.h
Correcting this definition doesn't actually change the value, since the sizes of the `length` and `offset` fields of `LangTagRecord` are identical to those of the `NameRecord`.
This is a bug fix for #1636 name table LANG_TAG_REC_SIZE size definition.
Since this doesn't actually have any effective change, I didn't run the tests (which I still haven't been able to get fully working yet).
=> [spot] fix name table LANG_TAG_REC_SIZE size definition.

c/makeotf/lib/hotconv/name.c
This fixes https://github.com/adobe-type-tools/afdko/issues/1643 [hotconv] 'name': memory leak in addName().
As I've mentioned before, I still don't have testing figured out locally on my end, so I'll submit this and see how the tests do on your end.
=> [hotconv] 'name': fix memory leak in addName()

README.md
LGTM.com no longer exists https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
=> Remove LGTM badges [skip ci]

c/makeotf/lib/hotconv/hot.c
This is a fix for #1653.
I ran tests locally and they all passed except the infinite loop one which always crashes for me.
It seems like it might be useful to have a new test that checks for that warning but I don't yet know enough about the testing framework to be able to write one myself.
=> [hotconv] fix warning for negative TypoLineGap.

c/makeotf/lib/hotconv/hot.c
This is a patch to fix bug #1647. Basically, I moved the static `dsigCount` variable outside the `refillDSIG()` function, and reset it in `hotReuse()`.
I think I finally have all local tests working except for `test_infinite_loop_with_dflt_lookups_bug965()`. That test fails before and after my changes, so I don't think it'd be related.
Unlike the previous bugs I've encountered , this strikes me as one that could probably use a test? The thing is, as I've mentioned elsewhere, I'm not sure if it's possible to trigger this bug using existing tools, and I'm still in the process of learning Python enough to write a test. If you think it warrants a test and could create one, that would certainly help in my learning process.
=> [hotconv] reset dsigCnt in hotReuse() so subsequent conversions add full stub 'DSIG' table.

requirements.txt
to accept more versions.
Should fix #1660 
* currently, setup.py changes '==' to '>=' but we had set fontTools to '<=' due to an earlier issue where we had to pin the version number. We no longer need to pin the version number, so we're changing it back to '=='.
* as Miguel mentioned, we should add support for more string replacement cases in setup.py — I'll look at that in a few days, but pushing this PR first to get a pre-release out for issue #1660 .
=> [requirements.txt] change fontTools version from '<=' to '=='

python/afdko/buildcff2vf.py, tests/buildcff2vf_test.py
What the title says. Fixes #1667.
=> [buildcff2vf] Don't return zero when input requires compatibilization

python/afdko/otfautohint/__main__.py, python/afdko/otfautohint/autohint.py
#1697 barfs w/o any arguments
#1699 cannot specify glyphs by GID
#1700 cannot specify glyphs via external glyph list
#1701 -h reports wrong tool name
Fixes the listed bugs. Some notes:
1. We fix the hyphen problem by looking for the token in the glyph list, if we find it we treat it like a simple name rather than a range.
2. I left the convention where you can specify a glyph range with normal names rather than GIDs or CID names, because it seems harmless and potentially useful after the other fixes
Some of this could be improved further (like the glyph list file format) but given how long its been broken, maybe this level is sufficient. 
Closes #1697 
Closes #1699 
Closes #1700 
Closes #1701
=> Fix otfstemhist bugs

.gitignore, c/sfntedit/source/Efile.c, c/sfntedit/source/main.c, tests/sfntedit_test.py
Modified sfntedit code to show the correct filename when non-existing file is specified for adding a table (`-a` mode).
Closes #1658
=> [sfntedit] Fix bug when attempting to add non-existent file

c/makeotf/include/hotconv.h, c/makeotf/lib/hotconv/GPOS.c, c/makeotf/lib/hotconv/GSUB.c, tests/makeotfexe_data/expected_output/bug1349.ttx
Add guards for h->otl == NULL in GSUB and GPOS code. Previously this was not explicitly checked, but could be NULL resulting in segfault.
=> add guards for h->otl == NULL before calling otlSubtableAdd

.github/workflows/testpythonpackage.yml, README.md
Add Python 3.11 to the testing matrix and update the README.md description of supported Python versions.
=> Add Python 3.11 to CI test matrix

c/shared/source/t1write/t1write.c, c/shared/source/tx_shared/tx_shared.c, c/shared/source/uforead/uforead.c, tests/tx_test.py
Upcoming `gcc-14` enabled a few warnings into errors. This exposed build failures related to pointer type confusion.
=> Fix build failures discovered by an upcoming `gcc-14` release

python/afdko/makeinstancesufo.py
This slightly alters the behaviour of makeinstancesufo’s postProcessInstance. clearCustomLibs now keeps all lib keys that start with `public.`.
fixes adobe-type-tools/afdko#1746
=> [makeinstancesufo] keep all public lib keys in instances

.github/workflows/asan.yml, .github/workflows/run_cvg.yml, .github/workflows/testpythonpackage.yml, README.md, setup.py
With the imminent final release of Python v3.13, v3.8 is also reaching its EOL. See [status of Python versions](https://devguide.python.org/versions/).
Enables Python v3.12 and drops v3.8.
=> [ci] Enable Python v3.12 and drop v3.8

c/shared/uforead.cpp, c/shared/ufowrite.cpp, docs/CIDKeyedUFOGuide.md, tests/tx_data/expected_output/cid_roundtrip/testCID-noFDSelect.ufo/fontinfo.plist, tests/tx_data/expected_output/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/cid00000.glif, tests/tx_data/expected_output/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/cid17899.glif, tests/tx_data/expected_output/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/cid17900.glif, tests/tx_data/expected_output/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/cid17901.glif, tests/tx_data/expected_output/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/contents.plist, tests/tx_data/expected_output/cid_roundtrip/testCID-noFDSelect.ufo/lib.plist, tests/tx_data/expected_output/cid_roundtrip/testCID-noFDSelect.ufo/metainfo.plist, tests/tx_data/input/cid_roundtrip/testCID-noFDSelect.ufo/fontinfo.plist, tests/tx_data/input/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/cid00000.glif, tests/tx_data/input/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/cid17899.glif, tests/tx_data/input/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/cid17900.glif, tests/tx_data/input/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/cid17901.glif, tests/tx_data/input/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/contents.plist, tests/tx_data/input/cid_roundtrip/testCID-noFDSelect.ufo/glyphs/layerinfo.plist, tests/tx_data/input/cid_roundtrip/testCID-noFDSelect.ufo/layercontents.plist, tests/tx_data/input/cid_roundtrip/testCID-noFDSelect.ufo/lib.plist, tests/tx_data/input/cid_roundtrip/testCID-noFDSelect.ufo/metainfo.plist, tests/tx_test.py
Originally we based the CID-keyed UFO workflow on all of the Adobe CJK fonts which have multiple font dicts, but we failed to account for the possibility of a totally valid CID-keyed file with no font dicts (no FDSelect because there are no FDArrays to point to). This adjusts the reading and writing of UFOs to properly handle this. The documentation is also updated so that we do not absolutely require the postscriptFDArray key in the lib.plist since it's actually optional.
=> Fix handling of CID-keyed UFOs with no FDSelect
