- FDK/Tools/Programs/autohint/source/main.c
The be and info file can be supplied by argument directly. If you use the -b command, the output will go to stdOut.
> Add option to not need to use files for autohint

- FDK/Tools/Programs/tx/source/tx.c
as noted here (https://github.com/adobe-type-tools/afdko/issues/20), on Windows the stdio.h tmpfile function tries to create temporary files in the root folder, thus requiring adminstrative privileges.
I only patched the tx command, but I know the same issue affects all the afdko commands which use tmpfile.
Anyway, here is my workaround. Maybe somebody could help me find a better place for this code, so that it can be reused in other parts of the library...
thank you,
C.
> [tx] make temporary files in the user's %TMP% folder on Windows

- FDK/Tools/SharedData/FDKScripts/BuildMMFont.py
> Fix typo in BuildMMFont.py

- FDK/Tools/SharedData/FDKScripts/ttxn.py
Should fix #115 
@Arno-Enslin please confirm.
Thanks
> [ttxn] catch GetoptError raised by ttx.parseOptions when no input file is provided

- FDK/FinishInstallLinux
- FDK/FinishInstallOSX
- FDK/Tools/SharedData/FDKScripts/FinishInstallWindows.py
The output of FinishInstallOSX was quite unreadable.
I wrapped every output to 70 characters, and made some minor optimizations.
> Improve output & wrapping of FinishInstall... scripts.

- FDK/Tools/Programs/CID_font_support/mkicf.pl
See https://www.microsoft.com/typography/otspec/baselinetags.htm
> [mkicf.pl] Fix vertical baseline tags

- FDK/Tools/SharedData/FDKScripts/MakeOTF.py
- makeotf won't run due to the syntax error
> [makeOTF] Fix syntax error

- FDK/Tools/SharedData/FDKScripts/otc2otf.py
- FDK/Tools/SharedData/FDKScripts/otf2otc.py
Just updating the version number and change dates to reflect the changes in moyogo & miguelsousa's recent commits.
> Updating version number and change dates for otc2otf.py and otf2otc.py

- FDK/Tools/SharedData/FDKScripts/CheckOutlinesUFO.py
minor changes in whitespace & sorting of a glyph list
> Syncing CheckOutlinesUFO.py v1.21 from Perforce to GitHub

- FDK/Tools/SharedData/FDKScripts/CheckOutlinesUFO.py
This is a first pass at preparing the code to work with Python 3 and making it PEP 8 compliant. More work is needed, but I think there are enough changes to warrant checking this in now. I also cleaned up many (but not all) issues reported by flake8 and PyCharm.
> First pass at code cleanup of CheckOutlinesUFO.py

- afdko/Tools/SharedData/FDKScripts/ConvertFontToCID.py
- afdko/Tools/SharedData/FDKScripts/ufoTools.py
(these checks were mistakenly replaced with non-equivalent checks during the recent pylint cleanup)
> Fixing checks of None in ufoTools.py & ConvertFontToCID.py

- afdko/Tools/SharedData/FDKScripts/makeInstancesUFO.py
- setup.py
(also removed other unused imports from makeInstancesUFO.py)
> remove use of robofab from setup.py and makeInstancesUFO.py

- afdko/Tools/Programs/makeotf/makeotf_lib/api/hotconv.h
- afdko/Tools/Programs/makeotf/makeotf_lib/source/hotconv/cmap.c
> Cmap format4 fixes2

- .travis.yml
@cjchapman I've also regenerated the token.
> [travis] Replace bare Slack token

- .travis.yml
(and continue to build for PRs from any branch)
> Travis only build for pushes to master

- .appveyor.yml
you should replace the pypi credentials and encrypt the password by going to 'Account → Encrypt data' tool on Appveyor website
see https://www.appveyor.com/docs/build-configuration/#secure-variables
> appveyor: deploy windows wheel on tagged commits

- .travis.yml
- .travis/before_deploy.sh
- .travis/build_manylinux_wheel.sh
- .travis/deploy.sh
- afdko/Tools/Programs/BuildAll.sh
- afdko/Tools/Programs/BuildAllLinux.sh
- setup.py
fixes https://github.com/adobe-type-tools/afdko/issues/251
> build manylinux1 wheel for Linux python2.7

- README.rst
This got broken after the project got reset
> Update AppVeyor's badge link

- afdko/Tools/SharedData/FDKScripts/CheckOutlinesUFO.py
- afdko/Tools/SharedData/FDKScripts/ConvertFontToCID.py
- afdko/Tools/SharedData/FDKScripts/ufoTools.py
Found these by running 'python3 -m pytest'
> Python 3 import fixes

- requirements-dev.txt
- requirements.txt
(instead of exact version match)
> fix for #408: change requirements files to check for compatible versions

- afdko/Tools/Programs/public/lib/source/uforead/uforead.c
- afdko/Tools/Programs/public/lib/source/ufowrite/ufowrite.c
- afdko/Tools/Programs/tx/source/tx.c
@miguelsousa (and everyone): I'm using this PR to test the effects of various tx related fixes on AppVeyor, one commit at a time. I'll let you know when I'm done.
> fix tx related issues

- Tests/makeotf_test.py
- afdko/Tools/SharedData/FDKScripts/MakeOTF.py
> [makeotf] Ignore trailing slashes in input font path

- .coveragerc
These changes get it fixed. See https://codecov.io/gh/adobe-type-tools/afdko/branch/fix-coverage
> Fix coverage configuration

- python/afdko/makeotf.py
- tests/makeotf_data/expected_output/bug497/opts-bit7n-bit8n-bit9n.ttx
- tests/makeotf_data/expected_output/bug497/opts-bit7y-bit8n-bit7n-bit8y.ttx
- tests/makeotf_data/expected_output/bug497/opts-bit7y-bit8n-bit9n.ttx
- tests/makeotf_data/expected_output/bug497/opts-bit7y-bit8y-bit9y.ttx
- tests/makeotf_data/expected_output/bug497/opts-ga.ttx
- tests/makeotf_data/expected_output/bug497/opts-gf-ga-nga.ttx
- tests/makeotf_data/expected_output/bug497/opts-gf-ga.ttx
- tests/makeotf_data/expected_output/bug497/opts-gf-nga-ga.ttx
- tests/makeotf_data/expected_output/bug497/opts-gf-nga.ttx
- tests/makeotf_data/expected_output/bug497/opts-gf.ttx
- tests/makeotf_data/expected_output/bug497/opts-nga.ttx
- tests/makeotf_data/expected_output/bug497/opts-r-ga-gf.ttx
- tests/makeotf_data/expected_output/bug497/opts-r-ga.ttx
- tests/makeotf_data/expected_output/bug497/opts-r-gf.ttx
- tests/makeotf_data/expected_output/bug497/opts-r-nga.ttx
- tests/makeotf_data/expected_output/bug497/opts-r.ttx
- tests/makeotf_data/expected_output/bug497/opts.ttx
- tests/makeotf_data/input/bug497/feat.fea
- tests/makeotf_data/input/bug497/fmndb.txt
- tests/makeotf_data/input/bug497/goadb.txt
- tests/makeotf_test.py
Fixes #497 and gets the file further cleaned up.
> makeotf fixes

- tests/runner.py
Fixes `OSError: [Errno 24] Too many open files`
> [runner] Close temporary files

- .travis.yml
- c/detype1/source/detype1.c
* reformatted `detype1.c` with `clang-format` and a little bit of hand editing
* also moved `flake8` & `cpplint` checks to `before_script` section of `.travis.yml` so they'll stop the build if they fail (fixes #517)
> cleanup detype1

- .appveyor.yml
- .travis.yml
- c/makeotf/makeotf_lib/source/cffread/cffread.c
- c/makeotf/makeotf_lib/source/cffread/t13fail.c
* reformatted code using `clang-format`
* added `cpplint` checks of the code in Travis and AppVeyor
> cleanup makeotf's cffread

- .appveyor.yml
- .travis.yml
- c/type1/source/type1.c
(used clang-format and a little bit of hand-editing)
> reformatted type1.c

- .appveyor.yml
- .travis.yml
- c/makeotf/source/cb.c
- c/makeotf/source/cbpriv.c
- c/makeotf/source/fcdb.c
- c/makeotf/source/file.c
- c/makeotf/source/include_files/cb.h
- c/makeotf/source/include_files/fcdb.h
- c/makeotf/source/include_files/file.h
- c/makeotf/source/include_files/lctype.h
- c/makeotf/source/include_files/lerrno.h
- c/makeotf/source/include_files/lstdio.h
- c/makeotf/source/include_files/lstdlib.h
- c/makeotf/source/include_files/lstring.h
- c/makeotf/source/include_files/package.h
- c/makeotf/source/mac/mac.c
- c/makeotf/source/main.c
- c/makeotf/source/makeotflib.h
* reformatted makeotf/source using `clang-format` + hand-editing
* remove some obsolete version control related comments
* added cpplint of makeotf/source to Travis & AppVeyor
> cleanup makeotf source

- .appveyor.yml
- .travis.yml
- c/public/lib/source/absfont/absfont.c
- c/public/lib/source/absfont/absfont_afm.c
- c/public/lib/source/absfont/absfont_compare.c
- c/public/lib/source/absfont/absfont_desc.c
- c/public/lib/source/absfont/absfont_draw.c
- c/public/lib/source/absfont/absfont_dump.c
- c/public/lib/source/absfont/absfont_metrics.c
- c/public/lib/source/absfont/absfont_path.c
* reformatted absfont source using clang-format + hand-editing
* added cpplint of absfont to CI
> cleanup absfont

- .appveyor.yml
- .travis.yml
- c/sfntdiff/source/Dda.c
- c/sfntdiff/source/Dda.h
- c/sfntdiff/source/Ddesc.c
- c/sfntdiff/source/Ddesc.h
- c/sfntdiff/source/Dfile.c
- c/sfntdiff/source/Dfile.h
- c/sfntdiff/source/Dglobal.c
- c/sfntdiff/source/Dglobal.h
- c/sfntdiff/source/Dhead.c
- c/sfntdiff/source/Dhead.h
- c/sfntdiff/source/Dmain.c
- c/sfntdiff/source/Dname.c
- c/sfntdiff/source/Dname.h
- c/sfntdiff/source/Dopt.c
- c/sfntdiff/source/Dopt.h
- c/sfntdiff/source/Dpriv.c
- c/sfntdiff/source/Dsfnt.c
- c/sfntdiff/source/Dsfnt.h
- c/sfntdiff/source/Dsys.c
- c/sfntdiff/source/Dsys.h
- c/sfntdiff/source/Dtto.c
- c/sfntdiff/source/Dtto.h
- c/sfntdiff/source/Mac/otfcomparelib.h
- c/sfntdiff/source/Win32/otfcomparelib.h
- c/sfntdiff/source/numtypes.h
- c/sfntdiff/source/osx/otfcomparelib.h
* reformatted sfntdiff code using clang-format + hand-editing
* added cpplint of sfntdeff to CI
> cleanup sfntdiff

- .appveyor.yml
- .travis.yml
- c/sfntedit/source/Eda.c
- c/sfntedit/source/Eda.h
- c/sfntedit/source/Efile.c
- c/sfntedit/source/Efile.h
- c/sfntedit/source/Eglobal.c
- c/sfntedit/source/Eglobal.h
- c/sfntedit/source/Emsgs.c
- c/sfntedit/source/Emsgs.h
- c/sfntedit/source/Esys.c
- c/sfntedit/source/Esys.h
- c/sfntedit/source/Win32/otftableeditor.h
- c/sfntedit/source/mac/teditlib.h
- c/sfntedit/source/main.c
- c/sfntedit/source/otftableeditor.h
- c/sfntedit/source/otter.h
* reformatted code using clang-format + hand-editing
* added cpplint of sfntedit to CI
> cleanup sfntedit

- python/afdko/checkoutlinesufo.py
- python/afdko/makeotf.py
- python/afdko/pdfgen.py
- python/afdko/pdfutils.py
- tests/buildmasterotfs_test.py
- tests/makeotf_test.py
> [makeotf] Fix makeRelativePath

- .gitignore
> add Visual Studio Code directory to .gitignore

- python/afdko/otf2ttf.py
changes from https://github.com/fonttools/fonttools/pull/1332
> otf2ttf improvements

- requirements.txt
> Add ufoProcessor to list of dependencies

- c/public/lib/source/cffwrite/cffwrite.c
- c/public/lib/source/cffwrite/cffwrite_share.h
- c/public/lib/source/cffwrite/cffwrite_t2cstr.c
- tests/tx_test.py
> [tx] update font bounding box when writing cff

- c/mergefonts/source/mergeFonts.c
- c/public/lib/api/absfont.h
- c/public/lib/source/absfont/absfont_afm.c
- c/rotatefont/source/rotateFont.c
- c/tx/source/tx.c
- tests/tx_data/expected_output/type1.afm
- tests/tx_data/expected_output/ufo2.afm
- tests/tx_data/expected_output/ufo3.afm
- tests/tx_test.py
> [tx] recalculate font bounding box when writing AFM

- c/public/lib/source/absfont/absfont_afm.c
* simplified while loop used to copy temp file to output file
* fixed signed/unsigned formatting issue reported by Codacy
> [tx] minor afm code cleanup

- c/mergefonts/source/mergeFonts.c
- c/rotatefont/source/rotateFont.c
(mostly a port of fixes from tx.c)
> cleaned up xcode build warnings

- python/afdko/resources/AGD.txt
> synchronized AGD.txt with internal version

- docs/OpenTypeFeatureFileSpecification.md
> Format A value records must not have angle brackets.

- tests/makeotf_test.py
removed decorator definition and 1 instance
> [tests] remove xfail_py27_mac decorator

- c/public/lib/source/t2cstr/t2cstr.c
The structure `_t2cCtx` is about 600k in size and thus should be in the heap, not on the stack, hence this change. (Also added a `memset` to explicitly initialize it full of zeros.)
> [t2cstr] move _t2cCtx off the stack (and init with zeros)

- c/makeotf/makeotf_lib/source/hotconv/cmap.c
- c/makeotf/makeotf_lib/source/typecomp/parse.c
- c/makeotf/source/cb.c
- c/public/lib/source/absfont/absfont_path.c
- c/public/lib/source/t1write/t1write.c
- c/spot/source/GSUB.c
- c/spot/source/sfnt.c
* fixed some uninitialized memory issues identified by static analysis
* also removed some superfluous lines of code
> fix uninitialized memory issues

- README.md
- docs/AFDKO-Overview.md
- docs/FDK_Build_Notes.txt
> [docs] Remove Python 2.7-related info [skip ci]

- c/spot/source/GSUB.c
- c/spot/source/cffread.c
- c/spot/source/kern.c
- c/spot/source/main.c
- c/spot/source/name.c
- c/spot/source/opt.c
- c/spot/source/opt.h
- c/spot/source/proof.c
- c/spot/source/res.c
- c/spot/source/sfnt.c
- c/spot/source/sfnt.h
Static analysis driven code cleanup:
* fixed some memory leaks
* fixed some uninitialized memory
* fixed some compiler warnings
* removed some dead and superfluous code
> [spot] fix memory leaks and uninitialized memory

- c/public/lib/source/pstoken/pstoken.c
general:
* cast indices for `class[]` to `uint8_t` to prevent negative index with `c >= 0x80`
* cast indices for `digits[]` to `uint8_t` to prevent negative index with `c >= 0x80`
`pstSetPlain()`:
* limit reading of bytes from cipher to the actual length of the cipher
* reset `h->mark` to `h->src.next` so `(h->src.next - h->mark)` will be current
> [pstoken] fix bounds issues

- c/type1/source/type1.c
(also remove a superfluous line of code)
> [type1] move 64k csbuf from stack to heap

- c/type1/source/type1.c
Free the csbuf that I malloc'd in PR #867.
(Also added some braces to make the code easier to read.)
> [type1] free csbuf

- c/public/lib/source/t1cstr/t1cstr.c
* changed a couple of attribute types for consistency
* removed an unused function
* reduced the scope of a variable
> [t1cstr] cleaned up some Xcode & cppcheck warnings

- c/public/lib/source/svread/svread.c
- c/public/lib/source/t1read/t1read.c
- c/public/lib/source/ttread/ttread.c
fixed several issues identified through static & dynamic analysis
> [tx] robustness improvements in svread, t1read, and ttread

- python/afdko/fdkutils.py
The previous version of this function that used `Popen.stdout.readline()` was failing intermittently in CI, so now we're trying this version that uses `Popen.communicate()`.
> [fdkutils] change run_shell_command_logging to use Popen.communicate

- python/afdko/makeinstancesufo.py
otherwise relpath errors may happen on Windows.
See https://github.com/fonttools/fonttools/issues/1735
> [makeinstancesufo] Save temp designspace file in the same dir as the original

- c/makeotf/makeotf_lib/source/hotconv/GPOS.c
- tests/makeotfexe_data/expected_output/bug993.ttx
- tests/makeotfexe_data/input/bug993/feat.fea
- tests/makeotfexe_test.py
> [makeotfexe] confirm that nextNode is not NULL before using it

- c/makeotf/makeotf_lib/source/hotconv/feat.c
- tests/makeotfexe_data/expected_output/bug1006.ttx
- tests/makeotfexe_data/input/bug1006/feat.fea
- tests/makeotfexe_test.py
> [makeotfexe] check that markClassNode is not NULL before using it

- python/afdko/agd.py
- python/afdko/comparefamily.py
- python/afdko/pdflib/fontpdf.py
- python/afdko/pdflib/pdfdoc.py
- python/afdko/pdflib/pdfgen.py
- python/afdko/ufotools.py
Some quick/easy fixes for issues reported by LGTM on:
- agd.py
- comparefamily.py
- fontpdf.py
- pdfdoc.py
- pdfgen.py
- ufotools.py
> [python] fix some low-hanging LGTM fruit

- python/afdko/pdflib/fontpdf.py
- python/afdko/pdflib/pdfgen.py
- unused variables in fontpdf.py
- unreachable code/unnecessary try/except for import of zlib in pdfgen.py
> [pdflib] Minor fixes for some LGTM.com issues

- README.md
> remove Codacy badge, add LGTM total alerts badge

- python/afdko/beztools.py
- python/afdko/checkoutlinesufo.py
Removed unnecessary `pass` in checkoutlinesufo.py and beztools.py
> [python] remove unnecessary `pass` statements

- c/spot/source/CFF_.c
- c/spot/source/glyf.c
- c/spot/source/sys.c
- c/spot/source/sys.h
- tests/spot_test.py
(also added test code to actually *check* the date and time produced)
> [spot] fix use of potentially dangerous function

- python/afdko/pdflib/fontpdf.py
- tests/proofpdf_data/expected_output/fontsetplot_otf_glyphs_2-7.pdf
- tests/proofpdf_test.py
> [proofpdf] Add support for --pageIncludeTitle option to fontsetplot

- docs/AFDKO-Overview.md
- add buildmasterotfs
- add buildcff2vf
- edit makeinstanceufo (clarify input file format)
- edit type1/detype1 (clarify direction of conversion)
[skip ci]
> Update AFDKO Overview

- requirements.txt
> [requirements] update requirements.txt

- requirements.txt
- tests/makeotfexe_data/expected_output/bug196.ttx
- tests/makeotfexe_data/expected_output/fealib/lookupflag.ttx
- tests/makeotfexe_data/expected_output/fealib/spec5fi2.ttx
- tests/makeotfexe_data/expected_output/spec/4d-2.ttx
- tests/makeotfexe_data/expected_output/spec/9b-3.ttx
- tests/makeotfexe_data/expected_output/spec/9b-4.ttx
- tests/otf2ttf_data/expected_output/ttf_ttf.ttx
- update to fontTools 4.4.3
- update expected TTX of some tests to reflect new fontTools output
> [tests][requirements] update requirements & tests

- .github/workflows/testpythonpackage.yml
- docs/OpenTypeFeatureFileSpecification.md
chained contextual lookups. Fixed typos.
> Updated STAT examples and multiple lookups applied to input on

- docs/OpenTypeFeatureFileSpecification.md
Fixed a couple internal links and added a few more.
> Fixed broken links and added new links in Document revisions.

- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- add PULL_REQUEST_TEMPLATE.md
- add CODE_OF_CONDUCT.md
- update CONTRIBUTING.md
> [docs] update various docs [skip ci]

- c/makeotf/makeotf_lib/source/hotconv/STAT.c
Add Format 2 check for min > max.
> Fix dupe checking for STAT Format 4 axis values. 

- .github/workflows/build_wheels.yml
Initial GHA Workflow definition. This is WIP in preparation for moving wheel-building into GitHub. It is not wired into the release cycle yet. It needs to be merged in order to be available for triggering, hence this PR.
> [dist] create workflow for building python wheels [skip ci]

- requirements.txt
Update psautohint to the latest release, v2.1.1
> [requirements] psautohint 2.1.1

- python/afdko/checkoutlinesufo.py
Make fixed length string for progress bar output.
> Update checkoutlinesufo progress bar

- .github/workflows/testpythonpackage.yml
- requirements.txt
- updated `requirements.txt` to use newly-released ufoNormalizer 0.5.0
- updated Test workflow to use Python 3.9 in the test matrix
Closes #1253
> Update ufoNormalizer, implement Python 3.9 in CI testing

- requirements.txt
Update requirements.txt to use psautohint v2.2.0 (latest release)
> [requirements] update psautohint

- .github/workflows/run_cvg.yml
- .github/workflows/testpythonpackage.yml
- add `pull_request` triggers to Test & Coverage workflows
> Update Coverage and Test workflows

- requirements.txt
- tests/buildcff2vf_data/expected_output/STAT_in_fvar.ttx
- tests/buildcff2vf_data/expected_output/STAT_infinite_range.ttx
- tests/makeotfexe_data/expected_output/fealib/bug1178.ttx
- tests/makeotfexe_data/expected_output/spec/9i-1.ttx
- tests/makeotfexe_data/expected_output/spec/9i-2.ttx
- tests/makeotfexe_data/expected_output/spec/9i-20.ttx
- tests/makeotfexe_data/expected_output/spec/9i-21.ttx
- tests/makeotfexe_data/expected_output/spec/9i-25.ttx
- tests/makeotfexe_data/expected_output/spec/9i-4.ttx
> [requirements] Update fontTools to v4.21.0

- NEWS.md
> Sync master to develop

- c/public/lib/api/t1cstr.h
- c/public/lib/api/t1read.h
- c/tx/source/tx.c
Bump versions for changes in #1321
> [tx] Bump versions for PR #1321

- c/public/lib/source/cffread/cffread.c
- tests/tx_data/expected_output/font.otf.dump3.txt
- tests/tx_data/expected_output/font.ttc.dump3.txt
- tests/tx_test.py
> [cffread.c] data type fix + add, update tests

- .github/workflows/build_wheels.yml
- .github/workflows/testpythonpackage.yml
Makes a few fixes and improvements to the Test and Publish workflows, now that the whole infrastructure is a bit more mature.
References that may help with reviewing these changes:
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
- https://github.com/pypa/gh-action-pypi-publish
- https://github.com/softprops/action-gh-release
- https://github.com/actions/create-release
> Fixes and improvements to GH Actions

- .github/workflows/build_wheels.yml
> Remove sudo from docker install

- .github/workflows/build_wheels.yml
Related to: #1377 , #1376, #1375, #1374
> [build_wheel.yml] Correct uuid package name for docker CentOS image

- .github/workflows/build_wheels.yml
- requirements-dev.txt
Related to an earlier fix in #1394
> [build_wheels.yml] Install cibuildwheel

- .github/workflows/build_wheels.yml
Resolving: a step cannot have both the `uses` and `run` keys
> [build_wheels] git config fix

- c/mergefonts/source/mergeFonts.c
- c/rotatefont/source/rotateFont.c
- c/tx/source/tx.c
Bump tx, mergefonts and rotatefont versions to 1.3.0
> [tx][mergefonts][rotatefont] bump versions to 1.3.0

- renovate.json
Load Renovate config before activating app. We are switching from PyUp to Renovate and it needs a bit of setup so as not to be too disruptive.
> [dependencies] add renovate.json

- c/shared/include/uforead.h
Update uforead.h version to 1.3.0 for #1556 PR
> [uforead.h] Update uforead version

- tests/tx_test.py
What it says on the tin.
Closes #1589
> Suppress copyright check in new UFO tests

- docs/OpenTypeFeatureFileSpecification.md
This is a non-code change that addresses a minor formatting/Markdown-to-HTML issue as reported in #1603.
> Formatting fix-up

- README.md
- requirements.txt
In relation to #1623 
~~- [ ] I have added **test code and data** to prove that my code functions correctly~~
~~- [ ] I have verified that new and existing tests pass locally with my changes~~
~~- [ ] I have performed a self-review of my own code~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
> [README.md] Add Warning about dropping Python 3.7

- requirements.txt
- tests/buildcff2vf_data/expected_output/CJKVar.ttx
- tests/buildcff2vf_data/expected_output/GSUBVar.ttx
- tests/buildcff2vf_data/expected_output/SHSansJPVFTest.ttx
Bump to latest fonttools version & update expected outputs.
Replaces #1622
> [requirements.txt][buildcff2vf_data] Update to fonttools v4.39.3

- README.md
Adding this so that we have clear instructions on how to create xcodeproj for debugging & development.
Do we need more detail?
> [README] Add instructions for creating xcodeproj

- requirements.txt
> Remove psautohint from requirements.txt

- tests/proofpdf_test.py
> Disable certain proofpdf tests that are failing for an unknown and seemingly spurious reason

- c/shared/t1write/t1write.cpp
Added some minimal error messaging to handle the errors in #1540 and #1632. This gives us the problem glyph instead of the generic `parsing failed` which tells us nothing about why or where. 
```
tx: --- orig-pearl-tangyuan.ufo
ERROR: Error in glyphEnd for glyph 'uni8D9F': inappropriate function call or arguments
FATAL: parsing failed
```
> Added some basic tx -t1 error messaging for #1540 and #1632
